### ISSUE TITLE
RE 0.8.2 to RE 0.9.0 and vice versa

### ISSUE THREAD

**Issue by jcplu** [rand256/valetudo#107]
Hello,
I installed too quickly the valetudo bin of the version 0.9.0 over the 0.8.2 one
and I send the command to restart the service > not working.
So I switched back the valetudo bin and reboot > now I can connect with ssh but the internet page doesn't work anymore.
How can I restore it ?
How can I save zones / spots ?
Thx

**Comment by rand256** [comment]
Generally 0.9.0 should work fine when installed over 0.8.2.

Which exactly command did you send to restart service? What last lines are written to /var/log/upstart/valetudo.log? Which base firmware version do you have installed?

**Comment by jcplu** [comment]
I used the command
` killall miio_client && service valetudo restart `

The log was the solution : I forgot to set file permission to 0755.
Thx for your help, It's working now.

Can you explain which directories we have to backup (like maps, sounds, ...) for the zones & spots ? other directories to backup ?
Thx

**Comment by rand256** [comment]
> killall miio_client

I rather wouldn't do that, it's not necessary and would only irritate rrwatchdog. Btw `service` command is missing on 2008 firmware onwards.

> Can you explain which directories we have to backup

All files related to firmware state is stored at /mnt/data/rockrobo, but if you want to replace them you need to stop _all_ roborock daemons first, otherwise it may lead you to quick factory reset. All valetudo configuration files are at /mnt/data/valetudo.

**Comment by jcplu** [comment]
My base firmware is v11_001886_re081 build using DustBuilder.

Telegram bot : all working except (probably because is not 2008) Spot, Rooms, and Goto.
After pushing disable/enable notifications, the sound volume seems lower.

How I can switch to firmware 2008 without loosing maps, zones, ... ?
Thx for this new release.

**Comment by rand256** [comment]
> After pushing disable/enable notifications, the sound volume seems lower.

This only switches receiving status updates from the vacuum (starting cleaning, going back to dock, charging etc). Spots & goto in telegrambot aren't working because of bugs (see #105), wait for next beta for a fix. Rooms require 2008 firmware.

> How I can switch to firmware 2008 without loosing maps, zones, ... ?

Flash firmware image as usual - either provided or build it yourself with _vacuum_ image builder by @zvldz. If everything goes well (in most cases) you'll get new firmware running having all the previous settings intact.

**Comment by nicedevil007** [comment]
Hey @rand256,  just won't open a new issue.
The title suits my question as well of this issue :)

I'm on 1898 with miio 3.3.9 right now.
If I want to update to 2008 with miio 3.3.9 and valetudo 0.9.x I just have to copy the URL of your precompiled packagefile (f.e. vacuum_valetudo_re_2008.pkg) and then go to my valetudo page and under settings / info / firmware update put in this URL right?

This will update the firmware safely as well as upgrading valetudo right?

**Comment by rand256** [comment]
It should. You'll also need md5 of the image (just text, not URL to file containing it).

**Comment by nicedevil007** [comment]
Ok, it is running right now. The Wifi is the same after this update or is there a new "open Wifi" where I have to set the credentials again after updating?

**Comment by rand256** [comment]
It's common update which should save all the settings including wifi if successful.

**Comment by nicedevil007** [comment]
Worked like you told us! Realy nice, thank you so far.

**Comment by jcplu** [comment]
Is it possible to downgrade from 0.9.x to 0.8.2 using info > settings > firmware update ?
and what about all the settings, will there be saved ?

Is it possible to keep also the command line in Telegram bot in RE 0.9.x, 
because sometimes a copy/paste can be faster ?

Sometimes when I delete many messages at once in Telegram (RE 0.8.2), 
an unselected one disappear and when I come back to Telegram bot, the message reappear.
Is it a bug from RE or from Telegram ?
Thx

**Comment by nicedevil007** [comment]
Did something changed on mqtt for mapdrawing from 0.8.2 to 0.9.x?
Map won't be displayed in node-red anymore now :(
My MQTT Settings are all in the conf file where I put them on 0.8.2 release.

**Comment by rand256** [comment]
Yes it did, the manufacturer has changed the map format for rooms support. At least some changes [like that](https://github.com/rand256/valetudo-mapper/commit/f9cb790d79d13ab835b437293d693ea5d863211b) are required to parse new maps, but that code still can't show room segments (if anybody needs them). Maybe I'll add them at some point.

**Comment by nicedevil007** [comment]
Mhhhh, for now I just want to send a MQTT command as I did before to my robot to let him clean my kitchen for example. If I go to your WebGUI and select my zone created in valetudo 0.8.x and then start the cleaning job everything is fine. If send the command with the specific MQTT layout my robot goes somewhere not the kitchen.

The payload I send to my robot is something like this:

`{"command":"zoned_cleanup","zone_ids":["kitchen"]}`

Is there anything more that we should add to this command to get the same behaviour as you do with valetudo zonecleaning?

**Comment by rand256** [comment]
That was a bug in 0.9.0 both betas. Should be fixed now.

**Comment by nicedevil007** [comment]
kk thank you! will report back tomorrow :)
installing newest relase right now.
Just last little question: If I'm on 2008 I don't have to do the send firmware update request stuff in the info tab right? just uploading the deb file and make dpkg -i *.deb file and that's it right?

**Comment by rand256** [comment]
Almost, you'll have to do something [like that](https://github.com/rand256/valetudo/wiki/Updating-valetudo-binary-on-2008--firmware) since there's no more dpkg in 2008.

**Comment by nicedevil007** [comment]
thanks, bookmarked :)

**Comment by jcplu** [comment]
Is it possible to downgrade from 0.9.0 to 0.8.2 using info > settings > firmware update ?
and what about all the settings, will there be saved ?

Is it possible to keep also the command line in Telegram bot in RE 0.9.x,
because sometimes a copy/paste can be faster ?

Editing rooms doesn't work for me, all the buttons are disabled when connected in http ?

**Comment by rand256** [comment]
> Is it possible to downgrade from 0.9.0 to 0.8.2 using info > settings > firmware update ?

I didn't try but can't see the reason why it may fail. Even if it won't work you always can manually do a factory reset and upgrade to 0.8.2 again from there.

> and what about all the settings, will there be saved ?

If the upgrade procedure finishes without issues, all the vacuuming settings should be preserved.

> Is it possible to keep also the command line in Telegram bot in RE 0.9.x,

It is definitely possible, but currently I'm not planning that.

> Editing rooms doesn't work for me, all the buttons are disabled when connected in http ?

They require selecting a room first. To rename or split you need to select exactly one room, to merge you need to select exactly two rooms. Otherwise the buttons are disabled.

If you don't have rooms on the map then your vacuum still haven't created them for you. In this case run full cleaning and allow the device to return back to the dock - and it should re-save the map with some rooms available.

**Comment by jcplu** [comment]
The zone can be defined as a room or merged rooms, so what's the advantage of the room feature ?

**Comment by rand256** [comment]
Maybe it's advantage mainly for mi home users since they don't have an ability to save zone sets. At least that was impossible when I used the official app a year ago. Also I can imagine rooms with complex configuration which may require multiple zones to fit. Anyway those who doesn't like rooms feature can disable it by a switch in settings, or could simply stay with older base firmware.

**Comment by jcplu** [comment]
Firmware update from 0.9.0 back to 0.8.2 works great.
