### ISSUE TITLE
No Map Data on MQTT topic

### ISSUE THREAD

**Issue by MrSolo570** [rand256/valetudo#135]
Hello,
I have the problem that mqtt is working but on the map data I can't get no map data.
I have installed Valetudo in the first place with a auto-built firmware from [](https://dustbuilder.xvm.mit.edu/ ) and afterwards copied the .deb-installation-file for valetudo re onto the robot and installed everything via ssh.
My config.json is configured like this:

`"mqtt": { "enabled": true, "identifier": "tachikoma", "topicPrefix": "valetudo", "autoconfPrefix": "homeassistant", "broker_url": "mqtt://mqtt:mqtt@192.168.188.45", "provideMapData": true, "mapSettings": { "drawPath": true, "drawCharger": true, "drawRobot": true, "border": 2, "scale": 4 }, "caPath": "" }, "dummycloud": { "spoofedIP": "203.0.113.1", "bindIP": "127.0.0.1" }, "webInterface": { "localization": "en", "hideMapReload": true, "style": "" }, "httpAuth": { "enabled": false, "username": "valetudo", "password": "valetudo" }, "telegramBot": { "enabled": false, "token": "", "password": "", "host": "", "proxy": "", "clients": [], "sendConsumables": true, "sendConsumablesEvery": false }, "allowSSHKeyUpload": true, "map_upload_host": "http://127.0.0.1"`

When I listend to mqtt topic "valetudo/#" I can see status messages but can't get no map data:
`Message 14 received on valetudo/tachikoma/state at 9:02 PM: { "state": "docked", "battery_level": 100, "fan_speed": "max" } QoS: 0 - Retain: true Message 13 received on valetudo/tachikoma/attributes at 9:02 PM: { "cleanTime": "169.5", "cleanArea": "8805.5", "cleanCount": 501, "last_run_stats": { "startTime": 1582372097000, "endTime": 1582373128000, "duration": 968, "area": "15.0", "errorCode": 0, "errorDescription": "No error", "finishedFlag": true }, "currentCleanTime": "16.1", "currentCleanArea": "15.0", "mainBrush": "130.5", "sideBrush": "30.5", "filter": "144.2", "sensor": "27.7", "state": "docked", "valetudo_state": { "id": 8, "name": "Charging" } }`

How can I fix the no map problem via mqtt? Thank you

**Comment by rand256** [comment]
If you expect to see parsed map data on mqtt and there's none, then you can find an explanation, for example, [here](https://github.com/rand256/valetudo/releases/tag/0.4.0-RE6). And this is not an issue, it's the intended behavior.

**Comment by MrSolo570** [comment]
Thank you so much for that insight. So basically not seeing any map related information when listening to valetudo/# is no sign of a malfunction?
I was aware of the existence of valetudo-mapper but thought it would use raw data published via mqtt to make into a png map and that one could listen to that raw data.

Because we're at it: what's meant by 

> As always, I remind everyone the necessity to use valetudo binary with valetudo.conf upstart script from this fork only, as it includes preparations for properly running the service that are missing in the origin script

from the link you posted? Do I have to make some additional changes before going with valetudo-mapper?

**Comment by rand256** [comment]
> So basically not seeing any map related information when listening to valetudo/# is no sign of a malfunction?

I don't know which tool do you use to "see" information in mqtt so I supposed that it may not show binary (raw) data cause it is not meant to be seen visually looking like garbage opposed to parsed data valetudo used to publish before version 0.4.0-RE6. If this is not the case, the other possible reason for the absence of map data is that the vacuum hasn't connected yet to the dustcloud which is integrated into valetudo. You may check that by visiting map tab on the web interface: if it shows empty map there then the device isn't connected. I'm not aware of other causes for map data not being sent to mqtt when 'provideMapData' flag set to true.

> from the link you posted? Do I have to make some additional changes

That is only a reminder for users who migrated to RE from origin valetudo by just copying a valetudo bin file - it advises them to replace old valetudo.conf to the RE version of it as well.

**Comment by MrSolo570** [comment]
I listened to valetudo/# via mqtt developer tools in Home Assistant. I could only see common status messages but nothing map related. Like you said I was expecting at least some raw data. Because I did not see any data I never even went for valetudo-mapper and tried to fix the mqtt map data problem first.
Now for the matter at hand, how can I see any mqtt data, what do I have to do to display it?

BTW: map is shown perfectly when I hit robots IP address

**Comment by Apocrathia** [comment]
I'm also not seeing anything come across on `prefix/identifier/map_data` on 0.9.0 (installed via deb package). I've got [valetudo-mapper](https://github.com/Poeschl/Hassio-Addons/tree/master/valetudo-mapper) already running and pointed at the correct topic, but again, no data. Here's my MQTT section of config.json, and my valetudo-mapper config (translated to YAML for the HA add-on).

```json
  "mqtt": {
    "enabled": true,
    "identifier": "downstairs",
    "topicPrefix": "vacuum",
    "autoconfPrefix": "discovery",
    "broker_url": REDACTED,
    "provideMapData": true,
    "caPath": "",
    "qos": 0
  },
```
```yaml
identifier: '#'
topicPrefix: vacuum
autoconfPrefix: discovery
broker_url: REDACTED
caPath: ''
mapSettings:
  drawPath: true
  drawCharger: true
  drawRobot: true
  drawForbiddenZones: true
  drawVirtualWalls: true
  border: 2
  scale: 4
  gradientBackground: true
mapDataTopic: 'vacuum/#/map_data'
minMillisecondsBetweenMapUpdates: 10000
publishMapImage: true
publishMapData: true
```
I've tried using the MQTT listener built into the HA Developer Tools section, Node-RED, and a HiveMQ client to view the MQTT data. I see the MQTT states, attributes, and discovery data. No binary map data.

The mapDataTopic value is set to a # because I have two vacuums, but it doesn't work even if I point it at a specific identifier.

**Comment by MrSolo570** [comment]
@aprosvetova where did you find this add-on? I searched on HACS and official addons but it gave me no results?!
Did you try to access the map via the webserver? get the mapper running and go to http://host:port/api/map/image . That way you at least  know that mapper and vacuum work.

I managed to download the repository, start it with "npm start" and actually get the map shown on the integrated web server. So basically this is proof for me that everything is working fine so far. 

How to use this as docker container? I can build the container but I dont understand how to map the config.json. If I map /app/config.json it always tells me config.json is a directory not a file.

**Comment by Apocrathia** [comment]
@MrSolo570 I just saw it mentioned a few times on the HA forums. It really should be in HACS.

I can get valetudo-mapper to start just fine via the add-on from Poeschl, but because nothing is coming over MQTT, the `api/map/image` URL simply returns "Not Found" in plain text. I don't have the `mapSettings` values in my vacuum's config.json, though. I thought that was specifically for valetudo-mapper.

Since you're able to get the map to show up in valetudo-mapper via a manual install, it may be an issue with the add-on. However, it looks like it's simply cloning in the repo, doing an `npm install` and `npm start`, along with some bashio output logging for the HA supervisor. So, I'm not sure where the hangup is.

The Dockerfile for valetudo-mapper is [in the repository](https://github.com/rand256/valetudo-mapper/blob/master/Dockerfile). Poeschl's version just maps the config to the HA UI, and passes port 3000 through Ingress.

**Comment by jokerigno** [comment]
Hi all, same issue here. 

I ugraded to 0.9.0 and mqtt is not working anymore. I didn't change settings and there's no error in valetudo log:
```

2020-03-04T02:33:09.932Z Loading configuration file: /mnt/data/valetudo/config.json
2020-03-04T02:33:10.420Z Dummycloud is spoofing 203.0.113.1:8053 on 127.0.0.1:8053
2020-03-04T02:33:10.423Z Webserver running on port 80
2020-03-04T02:33:15.032Z Probed last id = 1001 using get_status (2 retries)
2020-03-04T02:33:27.104Z Robot connected
2020-03-04T03:03:27.333Z Robot connected

```

Here's the config: 
```

  "mqtt": {
    "enabled": true,
    "identifier": "rockrobo",
    "topicPrefix": "valetudo",
    "autoconfPrefix": "homeassistant",
    "broker_url": "mqtt://xxx:xxx@192.168.x.xxx",
    "provideMapData": true,
    "caPath": "",
    "qos": 0
  },
```
How do I know mqtt is not working? Using MQTT Explorer.

**Comment by rand256** [comment]
Is it really the same?

This issue was about mapdata missing, and you seem not having mqtt connection at all, cause provided log part lacks the line "Connected successfully to mqtt server". This connection is done solely via third party [mqtt package](https://www.npmjs.com/package/mqtt), also there's an error handler set that should write something to logs in case it detects problems, and in this case it seems it detects nothing. I don't know how to add more logging for mqtt connection without cracking into mqtt package itself.

If you run your broken yourself, try starting it in some kind of debugging mode to see whether anything at all comes from the node to it.

**Comment by MrSolo570** [comment]
I was able to fix the problem. If you follow the steps I  took here https://community.home-assistant.io/t/xiaomi-vacuum-with-valetudo-re-how-to-map-zoned-cleaning-and-notifications-with-home-assistant/172282/21 maybe it can help you.

**Comment by jokerigno** [comment]
> Is it really the same?
> 
> This issue was about mapdata missing, and you seem not having mqtt connection at all, cause provided log part lacks the line "Connected successfully to mqtt server". This connection is done solely via third party [mqtt package](https://www.npmjs.com/package/mqtt), also there's an error handler set that should write something to logs in case it detects problems, and in this case it seems it detects nothing. I don't know how to add more logging for mqtt connection without cracking into mqtt package itself.
> 
> If you run your broken yourself, try starting it in some kind of debugging mode to see whether anything at all comes from the node to it.

ok maybe not the same (sorry for crossposting).

I found the error: valetudo mqtt client don't like special characters (# in my case) inside password. I changed it and now connection works.
But no error was visible inside logs.

**Comment by Apocrathia** [comment]
The configuration from @MrSolo570 worked. It appears that the following portion is missing from the MQTT configuration by default, causing the map data to not be published to the `map_data` topic.

```json
"mapSettings": {
      "drawPath": true,
      "drawCharger": true,
      "drawRobot": true,
      "border": 2,
      "scale": 4
    },
```

**Comment by rand256** [comment]
I'll just say that `mapSettings` portion is completely ignored in valetudo and required only in valetudo-mapper, where it generates by default.
