### ISSUE TITLE
Valetudo is lost after a few days

### ISSUE THREAD

**Issue by Sweatchuck** [rand256/valetudo#138]
Hello,

after a few days of use, valetudo deletes itself. 
The rooted version of the firmware remains, only valetudo is missing.

After I have reinstalled valetudo it works again for a few days and is then suddenly gone again.

I only have this phenomenon on one of my two robots. The other works permanently.

Can someone help me or tell how i can fix this error?

Thanks
Sweatchuck

**Comment by rand256** [comment]
Valetudo can't delete itself, it is the manufacturer's firmware (which works as a blackbox - can't be directly modified) may do some rollbacks to the previous state, where valetudo binary wasn't yet installed. Currently it is generally thought that this happens when filesystem gets damaged; it is checked right after every nightly reboot, and if there're appear to be some issues - firmware fires rollback or factory reset. And the reasons for issues with filesystem - either unclean shutdown or worn out flash memory.

It short, currently there's no solution to fixing that.

**Comment by radokristof** [comment]
@rand256 This is the same random-reset bug?
It only deletes some portion of the disk, does not rollback to the recovery version (which is a really old version - without valetudo obviously)?

Why does it restarts itself every night? I didn't knew this, already wanted to ask why I only get a few hours of uptime every time I check it...

**Comment by radokristof** [comment]
Unfortunately it happened to me also... It worked for 2-3 weeks.
Funny thing is the reset happened during a cleanup... 
Ps.: No it is not lost. It only disconnected Wi-Fi and I had to reconnect it. I was unable to do it with Valetudo, had to do it with the Xiaomi app.

**Comment by waclaw66** [comment]
It does to me on Gen1 every 3 weeks (2020-03-03 last time), today at 2:50 AM CET (as usual). Strange that after reset it has version 3452, although I installed valetudo RE 0.8.2 with 3468. I gonna try the new 0.9.2.

**Comment by radokristof** [comment]
That because it has a recovery partition which has a "fixed" firmware. It just replaces the current one with that one (which is an older version - I'm also sure to say that partition is a read-only memory). So it not just deletes valetudo.
For me it works now more than a month... so it is not the same for everyone...

**Comment by waclaw66** [comment]
Have you tried to somehow limit access of the cleaner to the internet? I added drop rules to cleaner's IP on my firewall, but it seems it didn't help. Assuming the reset is triggered from the cleaner itself.
> For me it works now more than a month... so it is not the same for everyone...

**Comment by radokristof** [comment]
It is surely something in the vacuum's firmware which does this (as access to Xiaomi clouds are already blocked in these Valetudo based hacked firmwares).
There might be some counter or something that triggers this firmware reset. Others said, excessive logging is causing the firmware reset, you can try to disable almost all logging (which is done by valetudo as a try).
The only thing I did is made a link to some folders in order to free up some space on the root partition (just to be able to do an apt upgrade), but it might be that's why my partition does not fill up completely which can also cause the firmware reset...

**Comment by pidator** [comment]
> I added drop rules to cleaner's IP on my firewall...

I've noticed an massive rise of log entries after doing the same. The reset happens because of errors in the filesystem/filesystem check, so starting to log more than needed will probably shorten the time till next reset.

**Comment by waclaw66** [comment]
Thanks for advice, I will check free space regulary.

**Comment by jdus** [comment]
> > I added drop rules to cleaner's IP on my firewall...
> 
> I've noticed an massive rise of log entries after doing the same. The reset happens because of errors in the filesystem/filesystem check, so starting to log more than needed will probably shorten the time till next reset.

So the physical storage becomes faulty?

**Comment by pidator** [comment]
> So the physical storage becomes faulty?

watchdoge monitors different processes and system states, when it detects an "failure", it automatically switches to an other system partition. The challenge is, to identify/discover what triggers the watchdoge to do so. See this issue in the hypfer repository https://github.com/Hypfer/Valetudo/issues/206 

On approch was to reduce the writing onto the system partition...

**Comment by rand256** [comment]
> watchdoge monitors different processes and system states, when it detects an "failure", it automatically switches to an other system partition

That's true, but AFAIK 99% of reported resets occurred right after nightly reboot, when watchdoge runs filesystem checks. And most likely filesystems got broken because of an unexpected nightly reboot.

**Comment by radokristof** [comment]
@rand256 I have disabled these nightly reboots with these scripts: 
https://github.com/MadJoker0815/roborock_nologs

I'm also pretty sure that at least most of the resets are caused by/after the nightly reboot...
Maybe if this helps on a longer basis, we can include these in this repo also?

**Comment by rand256** [comment]
> Maybe if this helps on a longer basis, we can include these in this repo also?

I personally didn't disable reboots on my Gen2 device but have no resets since the last summer. Generally, as far as I know there's no reports about random resets on so-called vacuumz firmware images (those from vacuumz.info), and because of that I don't see the substantial reason to hack into watchdoge.

**Comment by MadJoker0815** [comment]
root@rockrobo:~ uptime
 08:11:29 up 92 days, 10:51,  1 user,  load average: 1.07, 1.18, 1.16
root@rockrobo:~ df -h
Filesystem       Size  Used Avail Use% Mounted on
/dev/root        494M  280M  190M  60% /
devtmpfs         202M  4.0K  202M   1% /dev
none             4.0K     0  4.0K   0% /sys/fs/cgroup
tmpfs             30M  4.0K   30M   1% /tmp
none              50M  232K   50M   1% /run
none             5.0M     0  5.0M   0% /run/lock
tmpfs             50M  1.4M   49M   3% /run/shm
none             100M     0  100M   0% /run/user
/dev/mmcblk0p1   1.5G  155M  1.3G  11% /mnt/data
ext4             5.0M  4.0K  5.0M   1% /mnt/data/rockrobo/rrlog
/dev/mmcblk0p10  494M  279M  191M  60% /mnt/updbuf
/dev/mmcblk0p11   16M  1.5M   14M  10% /mnt/reserve
/dev/mmcblk0p6    62M   15M   45M  25% /mnt/default

Running Valetudo RE 0.9.2 on my Gen1 with FW. 3468 it is working flawlessly with my script.
This disables watchdoge at the time of reboot and does some cleanup on the filesystems while watchdoge is down"

Filesystem does not need to be broken to cause the reset. It just needs to be full. At first it activates the recovery partition (most users do not even notice that) and then when it it happens again do a factory reset. Essential is that this is not only happening if root FS is full but also on data or any other.
Thats why i run fstrim on all needed folders/partitions.

Sad thing is, that the new Gen2 FW is not having all the commands.

**Comment by rand256** [comment]
> Filesystem does not need to be broken to cause the reset. It just needs to be full.

I still highly doubt on that. I remember older reports of origin valetudo users who re-installed it after a factory wipe and got another reset just in 7-10 days - but there's no way for filesystem to be completely filled in 10 days if running normally.

Also there are checks for free space in rrlog daemon and I believe it would start removing its old logs in case /mnt/data is getting full. The only reason I've implemented rrlog-dir-to-RAM script in my firmware images was to reduce the number of unnecessary FLASH writes (to slower its wearing out), not to remove logs in precaution of low disk space.

**Comment by jdus** [comment]
I second that. My robo just reset 2 days ago and I kept an eye on the disk space usage. It was perfectly fine. I was asking for the physical storage becoming faulty because I was wondering how it would detect filesystem errors on a mounted partition. ~~But now I figure it will reboot every night, right?~~ Sry, yes it does, as you mentioned earlier.
