### ISSUE TITLE
"Can't decode payload" in mqtt

### ISSUE THREAD

**Issue by DBa2016** [rand256/valetudo#141]
No map data seems to be transferred correctly through MQTT. Home assistant log shows entries like:

"2020-02-24 20:21:54 WARNING (MainThread) [homeassistant.components.mqtt] Can't decode payload b'\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\x03\xed\x9d\x07\x80\x13\xc5\xfe\xf8\x13\x0f\x11....\x00' on valetudo/<rockrobo_name>/map_data with encoding utf-8 (for <f
unction MqttAttributes._attributes_subscribe_topics.<locals>.attributes_message_received at ..."

Happens every time I start the vacuum. The valetudo itself has a map on the "map" tab.

**Expected behavior**

**Screenshots**

Gen1 

0.9.0beta2

**Comment by rand256** [comment]
It is transferred correctly. The thing is since 0.4.0-RE6 the map data is published in native binary format as it is received from the firmware. It is not parsed to JSON by the vacuum anymore.

To get it working you may use valetudo-mapper companion application which can parse the map to the old format required by HA.

**Comment by DBa2016** [comment]
My bad - it was a matter of wrong case in the entity name. Not sure why HA was complaining about the "undecodable data" though, but I got this part running now.
