### ISSUE TITLE
No Map Data and cant SSH login

### ISSUE THREAD

**Issue by MeisterTR** [rand256/valetudo#151]
i just flash the 2008.pkg and the interface show no Mapdata and in top conecting... and 0% also i cant login via ssh wir pw. cleaner

![2020-03-07_07h17_33](https://user-images.githubusercontent.com/6328382/76138021-b856e800-6043-11ea-84b5-cdf7f8df4a1e.png)

**Comment by Krazy998** [comment]
also player doesnt start (managed to get in by pushing my public key via the interface) this image seems to be having alot of issues :(.

Also not sure if its valuable to provide the deb package as we cant install the deb file as there is no dpkg binary in the new 2008 firmware. I think Xiaomi has finally limped the firmware to the point its better to stay on the old one.

**Comment by rand256** [comment]
> i just flash the 2008.pkg and the interface show no Mapdata and in top conecting... and 0% also i cant login via ssh wir pw. cleaner

That's weird. Check if `cloud-dnsmasq` is running and you have both `VALETUDO` and `CLOUD-DNSMASQ` sections present in /etc/rc.local file. Also, do you have user `cleaner` in /etc/passwd?

> also player doesnt start

It is now called `rr_loader` in 2008.

> Also not sure if its valuable to provide the deb package as we cant install the deb

It still can be installed by all Gen1 users as well as pre-2008 Gen2 users.

**Comment by Stramm** [comment]
Same here:
- can't ssh login with root:cleaner
- no map data
- not possible to go back to a prior firmware using the web interface

Will create a key later and try to login that way.

**Comment by Stramm** [comment]
Pasting a public key using the webinterface and saving it works, however it's still not possible for me to log into the gen2. I will have to reset it...

**Comment by rand256** [comment]
So the cause of this is rc.local having some mixed line endings with CRLFs, and because of that some parts of it is never run. I'll reupload the corrected files soon. Sorry.

For those who are stuck with partially broken image flashed, you need to get inside by setting the public key in web interface (and this really works if done right) and run `sed -i $'s/\r$//' /etc/rc.local`, then `reboot`.

**Comment by Stramm** [comment]
Thanks works... the not working key was a win issue

**Comment by tripplet** [comment]
I had the same issue.
For me my public key did not work in the web interface because I switched all my keys to ed25519  some time ago.
The dropbear is to old in the new image to support ed25519 (the openssh pre 0.9 worked).
Generating a new rsa key was the solution.
It should be mentioned or dropbear should be updated to a newer version (if that is possible).
Thanks for your effort I can live with the current state, as everything works now. :thumbsup:
