### ISSUE TITLE
Viewing map from the cleaning history, error message "retry" appears

### ISSUE THREAD

**Issue by truresma** [rand256/valetudo#180]
Hello,

when I try to view the map from a cleaning history, I always get the error message "retry"

I Only want to see the map

When i click on the Map icon, the error comes, like in the screenshot that i attached.

Vacuum Model: Xiaomi Roborock S50

Valetudo Version: 0.9.2 2008 (newest one from github here)

![Anmerkung 2020-03-25 201725 jpg54353](https://user-images.githubusercontent.com/61728081/77576921-418c6c80-6ed6-11ea-8d10-a90eee9e8617.jpg)

**Comment by rand256** [comment]
Can't reproduce this. Actually, there definitely is a way to better implement map request code (with a loop or recursive call), but I'm afraid it won't change much in cases like you describe. That's because when it works properly, it always does exactly one "retry" reply on the first call and "ok" reply on the next one, almost regardless of the timeout between the calls. Default timeout in 0.9.2 is 1 second which is long enough, but I've run some tests having it reduced to a significant degree, but it worked for me anyway. So this makes me think that just running more requests in a loop might not help... I'm not sure.

In any case I'll rewrite that code for the next release. Meanwhile, does anybody have this issue too?

**Comment by pidator** [comment]
> Meanwhile, does anybody have this issue too?

Nope, never had an issue by viewing the previous cleaning maps!

@BlackRedM Have you tried a simple reboot of the robot yet?

**Comment by Stramm** [comment]
Nope, working as expected

**Comment by truresma** [comment]
did a reboot, nothing changed.

When the vacuum is not on the charging station it works sometimes, when it is on, than not ? ^^

**Comment by rand256** [comment]
Cleaning history map fetching was improved in 0.9.3, so if this still doesn't work then it is some error in the device's firmware, not in valetudo.
