### ISSUE TITLE
No Map Data

### ISSUE THREAD

**Issue by rpetteruti** [rand256/valetudo#196]
## To Reproduce

1. Go to 'the ip of the xiaomi vacuum with a browser'
2. Click on 'map button'
3. See "no map data"

### Vacuum Model

Gen1

### Valetudo Version

0.9.2

### User-Agent

Firefox 74.0
## Additional context

I've let the vacuum to do more than one complete clean of the house in order to let it build the map without luck.
Should I try to install the firmware y via the "firmware update" section on the valetudo web interface pointing to "https://vacuumz.info/download/gen1/vacuum_4007_valetudo_re_0_9_2.pkg" ?
Thank you

**Comment by pidator** [comment]
Sounds like you haven't installed valetudo properly... have you considered the files in deployment-section? with these files, there shouldn't be any connectivity to xiaomi cloud!

> Should I try to install the firmware y via the "firmware update" section on the valetudo web interface pointing to "https://vacuumz.info/download/gen1/vacuum_4007_valetudo_re_0_9_2.pkg" ?

Because you've already installed 3.5.4_4007 you'll first have to do an factory reset to downgrade the robot to an old miio version. With 3.5.4 it isn't possible to use the firmware update feature of Valetudo. But yes, you could use the mentioned firmware and with this firmware the xiaomi app can't be used anymore!

**Comment by rpetteruti** [comment]
Hello,
thank you for the reply, I've installed Valetudo RE using the "valetudo-re_0.9.2_armhf.deb" file with the command:
`dpkg -i valetudo-re_0.9.2_armhf.deb`
and then I've executed reboot.
There is something else that I should do? I didn't understand if with my current configuration my only option is to reset and install https://vacuumz.info/download/gen1/vacuum_4007_valetudo_re_0_9_2.pkg 
thank you.

**Comment by rand256** [comment]
Unfortunately for firmware images with miio client newer than v3.3.9 it is not enough to just install "valetudo-re_0.9.2_armhf.deb", because there were some changes made to them by manufacturer to prevent hacking into robot<->cloud connection, which is what valetudo exactly does.

So if you want to run new images rooted by yourself, you need either to downgrade miio client in them, or install [dnsmasq workaround](https://github.com/rand256/vacuum/commit/fdf5e52f671be75a548efc401d08419e31d9e289) to the device (for experienced users), otherwise valetudo won't be able to connect to it to get the maps. Other solutions: flash pre-rooted images which have some workarounds already integrated, or install older images that have miio version not higher than v3.3.9.

**Comment by rpetteruti** [comment]
Ok got it, so if I will install this image: https://vacuumz.info/download/gen1/vacuum_4007_valetudo_re_0_9_2.pkg this will have the miio client not higher than 3.3.9?

**Comment by rand256** [comment]
Yes, I believe it should work ok.

**Comment by rpetteruti** [comment]
Hi, I've just replaced the miio client with the content found here: https://github.com/rand256/vacuum/blob/master/custom-script/miio_3_3_9.tgz and now I have the map working!
Thank for the hint on the miio client version
