### ISSUE TITLE
Request to port mapdrawing to ICantBelieveItsNotValetudo

### ISSUE THREAD

**Issue by roflcoopter** [rand256/valetudo#20]
I am wondering if you think it would be easy/possible to port your way of drawing the map to the companion app [ICantBelieveItsNotValetudo](https://github.com/Hypfer/ICantBelieveItsNotValetudo). It looks way better in the Valetudo RE interface than it does in the official companion app. I took a look at it but got lost quickly... 

Maybe you could create a "ICantBelieveItsNotValetudo RE" version if you judge its not too much work.

**Comment by rand256** [comment]
That companion app is written and works in completely different way since it generates scalar images and Valetudo in fact produces vector graphics. Due to huge amount of limitations, it's almost impossible to recreate in ICantBelieveItsNotValetudo that map view as we see in normal Valetudo.

You may want to check [Lovelace Valetudo Map Card](https://github.com/TheLastProject/lovelace-valetudo-map-card) project for dynamic map generation. Hope you'll figure out on how to install it. I couldn't.

**Comment by rand256** [comment]
I've forked and modified a bit ICantBelieveItsNotValetudo as [valetudo-mapper](https://github.com/rand256/valetudo-mapper), but that's almost the only changeset that could be done for it. For any further ideas it should produce not a raster image but something else.

**Comment by roflcoopter** [comment]
Wow thanks, I'll check it out!
