### ISSUE TITLE
Navigation irritated by virtuals walls

### ISSUE THREAD

**Issue by MaluNoPeleke** [rand256/valetudo#234]
**Describe the bug**
After my S50 has analyzed the apartment for the first time with the firmware 2008 it splitted rooms not always correctly. Therefore I used the virtual walls feature to split rooms manually. Since then I cannot remove those virtual walls but whenever I use the map to send the robot to a specific room it cannot navigate there because it claims to not be able to reach them (not even trying to drive out of the first/initial room).
On the other side I have scheduled recurring cleaning rules for rooms and zones on a daily basis and with those the robot doesn't have any problems to drive to other parts of the apartment.

**Vacuum Model:** S5

**Valetudo Version:** 0.9.4

**Comment by rand256** [comment]
Valetudo is a GUI for manufacturer's firmware - it can't influence device's navigation itself at all.

Also I have no idea what do you mean by using virtual walls for room splitting. There's a page at "Zones" --> "Edit Rooms", which allows to split and merge segments. It is a bit tricky sometimes but with some patience and a few extra split/merges you can always get desired rooms configuration.

**Comment by MaluNoPeleke** [comment]
I used the "Edit rooms" feature to create the desired rooms and since then the robot doesn't want to drive "through" one of the virtual splitting lines and there sticks in the room with the docking station if I use the map feature. If the scheduled cleaning feature is used there doesn't seem to be this restriction. That's why I thought there could be a "Force navigation" feature that ignores those virtual borders and only uses the physical sensors.

**Comment by rand256** [comment]
There's no such feature.

Virtual walls (red) and segment border lines (blue) are completely different items and device can cross the latter whenever it needs to since it isn't an actual barrier - it is just displayed so.
![example](https://user-images.githubusercontent.com/30267719/82305758-c40d4600-99c6-11ea-89af-ea5c82b7660a.png)

Your issue is probably caused by something else - it's hard to tell without seeing the map.

**Comment by MaluNoPeleke** [comment]
I mean those white lines that were used to split rooms and stay now on the map.
In this example the robot doesn't drive outside of the kitchen ("Küche") if the door with the grey divider is closed (but the door at the white divider is of course open. 
![Screenshot_20200531-225525](https://user-images.githubusercontent.com/1446541/83362543-67306900-a392-11ea-8247-b8d8c28e86bf.png)

**Comment by rand256** [comment]
It's weird I thought I've already written some answer to this question. Did I forget to actually post it that time?..

Anyway, what you're talking about is the really old roborock issue with the closed doors: if the device "saw" that the door is closed, it will "think" that it is not a door but a permanent wall. It doesn't relate to room border lines. To make that closed door to be recognized as open again you need to make device "rescan" it via running some zoned cleaning around it. Otherwise it will continue thinking that there's no door and newer was, and will complain that it can't reach anything behind that. There's no solution for that unless manufacturer will do something about it.
