### ISSUE TITLE
"Room not found on current map" after switching between maps

### ISSUE THREAD

**Issue by lollul** [rand256/valetudo#239]
**Describe the bug**
I have a schedule saved to clean 3 rooms on one map (1st floor). Once I load a different map (2nd floor) and load back the earlier map (1st floor) the schedule won't work. I get an error: "Room not found on current map!"

I realize multiple map feature is experimental. But I wonder if there is a known workaround.

**How to Reproduce**
1. Load map 1
2. Set up schedule to clean rooms on map 1. (schedule will now work correctly)
3. Load map 2
4. Load back map 1
5. Schedule shows "Room not found on current map!"

**Expected behavior**
Scheduled room cleaning should work with multiple maps.

**Vacuum Model:**  Gen2 

**Valetudo Version:** 0.9.4

**Comment by rand256** [comment]
I'm afraid it might be beyond repair. The thing is manufacturer's software caches some already loaded maps (or some aspects of them) and after trying to reload them from the same path it simply doesn't care to drop the cached data. And I was unable to find a way how to make it do that manually except for slow and hackish way of restarting all the onboard roborock services.

However there are rumors new base firmware with official multifloor support is coming this year for gen2. Maybe it'll overcome these issues.

**Comment by zvldz** [comment]
Maybe you should run the 'sync' command.
Or does that not help ?

**Comment by rand256** [comment]
@zvldz, are you talking about Linux _sync(8)_? I didn't try that but quiet sure it won't help. I played with map preview-before-restore a while ago and there was a similar issue: it loaded only the first map (and seemed to cache it) and ignored all further attempts since it looks like it thought that the file was the same - as there's no "official" scenario where map files could be replaced my something other than AppProxy/rr_loader. Actually I was surprised that _recover_map_ miio command worked without such caching for the map itself, but seems not for the room names.

I wonder whether there's a way to patch manufacturer's software to somehow completely disable that map caching in both _recover_map_ and _get_recover_map_ miio commands, as all my attempts to find using ghydra the code doing that was a failure.

**Comment by zvldz** [comment]
Yes, I was talking about the linux command.
It might also help:
`sync; echo 3 > /proc/sys/vm/drop_caches `

If it doesn't help, the map is not cached at fs level.

**Comment by zvldz** [comment]
And then a patch on AppProxy is required.

**Comment by rand256** [comment]
Calling sync predictably didn't help. Though adding "reset_map" command just before calling "recover_map" looks promising in terms of reloading rooms data. But testing is still needed.
