### ISSUE TITLE
Can't resume zoned clean after error with mqtt

### ISSUE THREAD

**Issue by hammondses** [rand256/valetudo#244]
Hi there, I've read all the documentation I can & searched github, apologies if I missed it!

I'm wondering what the mqtt command is for resuming a zoned cleanup?

If I start a zoned clean and pause it, then send it the start command to /valetudo/rockrobo/command it resumes the zoned cleaning, it's only when it's in an error state that it doesn't seem to want to resume with that command.

My vacuum has the issue of 'error 5, remove and clean the main brush' while I'm waiting for a new brush to arrive. I've setup a sensor with home assistant to detect the error and send it a start command, which works for a full clean, but seems to just start a full clean if it's on zoned clean when it's sent. I'm currently using sending a 'start' command to /valetudo/rockrobo/command. I've tried start-pause but it doesn't seem to do anything for me.

Any help would be greatly appreciated!
Thanks!

**Comment by rand256** [comment]
Unfortunately there's no dedicated mqtt command for resuming zoned cleaning, and due to how it's coded right now it actually continues zoned cleaning _only_ upon receiving "start" while being paused. And in all other cases "start" just issues miio command to run full cleaning.

Is there a way for you to somehow clear "error" state without disrupting zoned cleaning, via WebUI maybe? Would using something like "stop" command cancel "error" state, or will it stop zoned cleaning too? Could you post the results from http://your_vacuum_address/api/current_status opened in your browser when the device is in error state during the zoned cleaning? Then I could probably change the code to allow running resuming command in the error state too, but I don't know whether the device actually will allow doing that.

**Comment by hammondses** [comment]
Here's the output from /api/current_status while it's stuck
`{"msg_ver":2,"state":2,"battery":82,"clean_time":780,"clean_area":9175000,"error_code":5,"map_present":1,"in_cleaning":2,"in_returning":0,"in_fresh_state":0,"lab_status":1,"fan_power":100,"dnd_enabled":1,"human_state":"Charger disconnected","human_error":"Main brush stuck","model":"roborock.vacuum.s5"}`

If I press the main start button on the vacuum itself, it'll resume zoned cleaning, just not doing it remotely :(.

Thanks!

**Comment by rand256** [comment]
Physical button press can't be simulated using available interfaces unfortunately nor we can see the logic what exactly it does in which circumstances. But I'm surprised the state is 2 (idle/sleep) instead of 12 (error). Is that a status right after the device got stuck or after ~10 minutes had passed? And what would happen with status if you send a "stop" command?

**Comment by hammondses** [comment]
Yeah that was after a while of it being stuck, I'll run it again and try catch it earlier. I'll then send a stop command and see what we get

**Comment by hammondses** [comment]
Didn't catch it quick enough, after stop it gives me this
![after stop](https://user-images.githubusercontent.com/21191206/83627440-08196100-a5eb-11ea-919b-5a7ec1719a6c.PNG)
Sending a start after stop gives this which is starting a new clean by the look of it :(
![after start](https://user-images.githubusercontent.com/21191206/83627475-17001380-a5eb-11ea-916a-9940994e5078.PNG)

**Comment by rand256** [comment]
So, we see that "stop" makes device exit "sleeping" state (2) and it returns to "error" state (12) which we assume it initially enters when the brush is first stuck. Now it would be interesting to know what happens when you call "stop" when it is in its "error" state: will it enter "paused" state (10) or rather reset to "idle" (3)? If it will back to "paused" state, then you should be able to simply call "stop" and then "start" again after each error of that kind.

Also I've uploaded this binary for testing: [valetudo-0.9.5-200603.tar.gz](https://erinome.net/valetudo-0.9.5-200603.tar.gz). I've changed it so it should allow "resuming" from error state too (not only from paused as it is now, and if the device's firmware is ok about that since we don't know for sure) by using common "start" mqtt command. You can update to it using [this quick guide](https://github.com/rand256/valetudo/wiki/Updating-valetudo-binary-on-2008-firmware).

**Comment by hammondses** [comment]
Yep it works! 

Sending a start via mqtt has it resuming the cleanup :D

Before and after sending start when error occurred. 
![before](https://user-images.githubusercontent.com/21191206/83938756-60d73c80-a82b-11ea-950a-2f3e18849aff.PNG)
![after](https://user-images.githubusercontent.com/21191206/83938758-63d22d00-a82b-11ea-91d4-1582c9c441a5.PNG)

Thanks a lot!
