### ISSUE TITLE
MQTT broken in 0.9.5.2?

### ISSUE THREAD

**Issue by nicedevil007** [rand256/valetudo#245]
Hey @rand256, 

it's me again. As I told you in my last 2 issues I got the 0.9.5.1 installed after 0.9.3.
I'm using the mqtt connection to automate my robot.

In 0.9.3 everything works like a charm. Same in 0.9.5.1.
Yesterday I updated to 0.9.5.2 for the map fix. Today my MQTT broker won't receive any message from the robot. Also there is no possibility to send a command to the robot.

I checked the new settings in den WebGUI for MQTT Setup and doublechecked the config file
`/mnt/data/valetudo/config.json` everything seems to be setup as it should be.

```
"mqtt": {
    "enabled": true,
    "identifier": "rockrobo",
    "topicPrefix": "valetudo",
    "autoconfPrefix": "homeassistant",
    "broker_url": "mqtt://USERNAME:PASSWORD@10.0.4.6:1883",
    "provideMapData": true,
    "caPath": "",
    "qos": 0
```

I just replace password and username with the real ones ;)

What I tested so far was:

- disabling mqtt
- enabling it after that
- restarted the robot
- checked other IoT devices if they are able to communicate with my mqtt broker (it was successfull)

nothing helped :(

**Comment by rand256** [comment]
If it worked for you in 0.9.5.1, then the issue is most likely not in valetudo, because there was no single change regarding MQTT after initial 0.9.5.

Try pinging your broker from the vacuum's console, also check /var/log/upstart/valetudo.log for errors though the chances to see something useful there are quiet low.

**Comment by nicedevil007** [comment]
No errors no loss of packets to my broker:

![grafik](https://user-images.githubusercontent.com/17103076/83495822-80cbd080-a4b8-11ea-8544-ddb7cf3ea7a7.png)

EDIT: Do we have a possibility to send a MQTT message manually from the console?

**Comment by rand256** [comment]
> Do we have a possibility to send a MQTT message manually from the console?

Nope, there's no such possibility... As we see in the log, it never gets connected since otherwise there would be a message logged about it.

Valetudo uses the [MQTT library](https://www.npmjs.com/package/mqtt) for connecting to the broker, and looks like the only way to get errors from it is subscribing to 'error' event: we already do that and still no errors is logged for you which looks suspicious. I really don't know what else to suggest. Right now I've connected my device to cloudmqtt.com's broker for testing and it works ok (though that broker is _very_ slow on free plan).

**Comment by nicedevil007** [comment]
trying to reflash the device with your latest release from the WebGUI and then recheck if everything works again.

Maybe it is possible for a future release to install mosquitto to get the possiblity to check manual connection to the mqtt broker.

EDIT: nope that didn't help :/

**Comment by nicedevil007** [comment]
Ok found a solution :)

Problem was sitting right in front of the screen.

I have a firewall rule that disables IPv4 Internet connection for the VLAN where my IoT devices are located.

After Updating I usually disable this... unfurtunately I disabled the TCP_1883 rule that is the only rule allowed on my IoT VLAN... so no comment... just big smile
