### ISSUE TITLE
[Feature Request] Chain multiple zone cleanups

### ISSUE THREAD

**Issue by cyko69** [rand256/valetudo#249]
Currently (at least on gen1) a zone cleanup command sent while a zone cleanup is active triggers nothing. It would be nice if valetudo would save the commands and starts the new zone cleanup after the old one has finished.

**Comment by ghost** [comment]
You can already do that by just adding more zones at once

**Comment by cyko69** [comment]
I am aware of that feature. What I want to do is to add more zones while the vacuum is already in zoned cleanup. Apart from being able to do just that, it would have the nice sideeffects that 
1. zones were cleaned up seperatly (for now when I clean multiple zones at one its treated like one big zone) and
2. I can set the order in which the zones were cleaned.

I hope its now more clear what I meant.

**Comment by radokristof** [comment]
I understand what you want, but most of them are already available now I think.
1) Why it is a big zone? For me every zone is treated normally. So basically when I start a zoned cleanup with more zones, it just like if I would start seperate zoned cleanups with one zone one after the other...

2) If you click the intended zones in the order you want to be cleaned, it will clean it that way (you can also see the indicator, indicating the position of the zone)

**Comment by rand256** [comment]
>  It would be nice if valetudo would save the commands and starts the new zone cleanup after the old one has finished.

I think this will be implemented along with the ability to run zoned cleaning with more than 5 zones selected simultaneously (by running multiple zoned cleaning commands one after another). The only thing I'm still not exactly sure of is how to properly decide when the "queue" should be cleared. 

I.e. the queue obviously should be kept on "pause" or "error" events and dropped on receiving a "stop" command. At the same time "start" after "pause" should probably drop it too, as you won't want to end with another cleaning suddenly continues to zones added to the queue during the previous cleaning attempt. And there are other possible scenarios as well.

**Comment by cyko69** [comment]
@radokristof your right, just tested it and it worked like you describe. Strange, could swear it wasnt so before.
@rand256 start after pause should clear the queue? Is start different from continue? I think it should only be cleared when a stop is received...

**Comment by rand256** [comment]
There are two separate miio commands for resuming zoned cleaning and starting new zoned cleaning.

So currently it works like this: if you start zoned cleaning, pause it and then call new zoned cleaning, it will abandon the first and start a new one. But if you have a cleaning with a queue, then starting a new cleaning will cancel only the currently handled zones leaving the rest of a queue behind. That's why I said about clearing it.

But strictly talking - yes, it can be reworked that way so the queue would be cleared only on stop, and do a remap of starting a new zoned cleaning to actually do a resume every time if the cleaning is in progress (including paused states). Would it be intuitive enough for those, who got used to possibility to start another cleaning not fully stopping the previous one? Idk.

**Comment by rand256** [comment]
This was implemented in 0.9.6:
You can enqueue another zoned or rooms cleaning while the cleaning is running.
