### ISSUE TITLE
It deletes a marked cleaning area if it could not reach it

### ISSUE THREAD

**Issue by v-a-d-e-r** [rand256/valetudo#251]
If the robot could not reach a set cleaning area, it deletes it in the map! That issue was not in older versions and seems to be new in the 0.9.5!?

**Comment by rand256** [comment]
It wipes user-defined zones from the map after a command to clean those zones has been actually sent to the device. It is in no way connected with reachability of the selected areas by the vacuum. I've made this change since at some point I was really tired of manually removing the previously specified zones every time I want to add some new non-saved zone after some other cleaning.

Though maybe that wasn't the best idea for everyone. I'll think about adding an option to Web Interface settings to decide whether to auto-remove such zones or not.

**Comment by rand256** [comment]
Actually as I understand the issue is there's no easy way to distinguish successful cleanup from the problematic cleanup on the Web UI, as then it would be possible to auto-remove zones only when their cleaning was finished without issues. Maybe it would be better to somehow implement this possibility.

**Comment by v-a-d-e-r** [comment]
Yep, that would be nice. I don't know if there is a parameter from the robot if the cleaning job was successful or not, but I hope so. ;-)
