### ISSUE TITLE
Feature Request: MQTT print list on zone/segments on demand

### ISSUE THREAD

**Issue by jfmcarreira** [rand256/valetudo#254]
It woudl be usefull to be possible to know the zones/segments available for cleaning.

For instance, it would be possible to make Home Assistant aware of the possible zone cleaning commands to send to the robot.

**Comment by rand256** [comment]
I'm not quiet sure how exactly it should work since I've never used Home Assistant or stuff like that, but I coded something like you've described. Could you try installing [this version](https://erinome.net/valetudo-0.9.5-20200615.tar.gz) of valetudo and check does it work for you?

What it does:
If you send a "custom command" called "get_destinations", it will publish to valetudo/rockrobo/destinations (by default, your prefixes may differ) the next JSON object:

```
{
   "spots": ["spot1","spot2", ...],
   "zones": ["zone1","zone2", ...],
   "rooms": ["room1", "room2", ...],
   "updated": unixtime_in_ms
}
```

If run on gen1 (or gen2 with an older firmware) "rooms" would always be an empty array. I've added a field called "updated" so it would be possible to differentiate a new message with an older one. Or should I make this message not "retained" instead? (All those messages published in valetudo are currently retained.) Or maybe just get rid of "updated" field?

**Comment by jfmcarreira** [comment]
I do not know if home assistant would have a feature prepared for this or not. But my idea is to based on this type of message processed the room names and do some extra code.

This seems excellent. I will give it a try later today. Thank you. I would assume the procedure would always be send get_destinations and read the result.

**Comment by jfmcarreira** [comment]
Can you point me out how to upgrade Valetudo RE? I only flashed my vacuum twice. Once with Valetudo and another with RE. And both cases it was a fresh installation after an hard-reset.

**Comment by pidator** [comment]
> Can you point me out how to upgrade Valetudo RE?

Check [this link](https://github.com/rand256/valetudo/wiki/Updating-valetudo-binary-on-2008-firmware).
