### ISSUE TITLE
Please upstream your improvements please

### ISSUE THREAD

**Issue by stevenroose** [rand256/valetudo#27]
I know you mention your improvements are hackish, but they are probably better than nothing especially as you seem to have fixed Valetudo issue #206.

**Comment by rand256** [comment]
There's no direct fix for #206 as nobody knows for sure why that happens unfortunately. I guessed a couple tricks that could lower the probability, and seems all of them are inside valetudo.conf script only.

As for features introduced in RE, I've seen Valetudo's author mentioned he wants to keep the app simple, and all of the features here are doing anything but not keeping it that way.

**Comment by alexkn** [comment]
I also think you should try to bring your extensions upstream.
You say yourself that your improvements are "hackishly".
So I have no really good feeling to use your fork productive.
With a pull request to the upstream repository, more people would check the code to get better code quality.
It will also be harder in the future to maintain extensions in upstream and your fork in parallel.

**Comment by rand256** [comment]
> You say yourself that your improvements are "hackishly".
> So I have no really good feeling to use your fork productive.

Don't you mind then that using any valetudo implies _hacking_ the device to get root access in the first place?

> It will also be harder in the future to maintain extensions in upstream and your fork in parallel.

I believe there will be no long-standing future extensions since all newer device models just can't be simply _hacked_ the way older roborock gen1 and gen2 were. Moreover, even if these models are still produced, when they'll start getting fw 4004+ for gen1 and 1910+ for gen2 from the factory, we won't be able to easily _hack_ them and get valetudo installed anymore.

For everything else - point noted. Thank you.
