### ISSUE TITLE
Map display got stuck

### ISSUE THREAD

**Issue by jdanders** [rand256/valetudo#272]
I installed Valetudo RE on my fresh S5 (never connected to wifi or called home to China) and things look pretty good. However, I set up a forbidden zone last night and now I can't seem to change it. The web interface reports "Successfully saved forbidden markers" but when I go back to the map, it's still there. I've tried moving, adding, and deleting, but nothing changes. Any ideas why?

**Comment by jdanders** [comment]
Sorry, looks like I reported early. It wasn't just forbidden zones that was broken, then entire map wouldn't update any more no matter what I did. A reboot of the robot fixed it. The last thing done was a multi-zone schedule (7 zones all together). The map was stuck showing the cleaning results of the last 2 zones it cleaned (the second part of the multi-zone run).

Unfortunately I don't know how to reproduce.

**Comment by rand256** [comment]
Well... If you run or schedule cleaning containing more than 5 zones, would it choke on it again?

Actually I've run a few tests some time ago and they completed fine, so I believe this shouldn't break. But I ask that since I personally almost never run such a lot of zones at the same time during my common device usage... as it seems my flat is too small for that. :\

**Comment by jdanders** [comment]
Well, it's been running every night on the multizone schedule, and I have not seen this issue repeat. Should we close it the issue? I can reopen if I see it happen again.
