### ISSUE TITLE
All timers disappear after multifloor cleaning

### ISSUE THREAD

**Issue by eeshaan** [rand256/valetudo#274]
Hi, @rand256 and team. Thanks for all the work you've done on this project.  
I know that multifloor features are experimental, but I've noticed that after cleaning another floor and switching back to the original, there are a few issues with timers. 
  
Namely:
1) _zoned cleaning_ scheduled zones are missing and the timers are reset.
2) room cleaning timers in _cleaning schedule_ are deactivated and show the error `Room not found on current map! (#0)`.

**How to Reproduce**

1. Switch to another floor.
2. Switch back.
3. Check timers.

**Expected behavior**

Separate zones and rooms with respective timers for each floor. Would be great if they were color coded as well.

**Screenshots**

<img width="498" alt="Screen Shot 2020-08-02 at 10 52 11 PM" src="https://user-images.githubusercontent.com/31187740/89144261-b9316e80-d53c-11ea-843d-a1de99404c2a.png">

**Vacuum Model** 
roborock.vacuum.s5

**Valetudo Version:** 
0.9.6

**Additional context**
Willing to work on this and open a PR. Waiting on 0.9.7 release first, though. Also curious if you'd be willing to let devs with UI/UX backgrounds add another modern theme in settings with a revamped design or if that kind of work would entail another fork (which probably isn't ideal because Valetudo is already fragmented).

**Comment by rand256** [comment]
> I've noticed that after cleaning another floor and switching back to the original, there are a few issues with timers.

Yes, room selection in scheduled room cleaning seems to be reset to zero (literally) by manufacturer's firmware when map loading method is "backup recovery". I'll take a look if I can workaround it. Meanwhile you could probably use "cleaning sequence" map loading method to keep chosen rooms intact. Though it would start scheduled cleaning in a wrong room if the device would be using another map when current time would match the timer...

As for scheduled zoned cleaning, in theory it shouldn't be affected by map reloading at all, since it is processed solely by valetudo, but it should have the same issue with starting on a wrong map. So it's quiet weird they get deactivated for you.

In general, you're definitely right and cleaning timers should work on per-map basis at least in a way like it's currently done for zones and spots. I think I'll work on that soon.

> Also curious if you'd be willing to let devs with UI/UX backgrounds add another modern theme in settings with a revamped design

Well, the only I can say I'll integrate a PR with a new theme if you'd make it.

**Comment by rand256** [comment]
I've just made a [test build](https://erinome.net/valetudo-0.9.7-20200804.tar.gz) that should tie timers settings to stored maps. It should work directly like zones per map save/restore feature:

- It save timers when storing a map;
- It reloads timers when restoring a map;
- If restored map doesn't have any data about timers (i.e. it is a map saved with a previous valetudo version), it keeps current timers set for a previous map.

**Comment by rand256** [comment]
Fixed in 0.9.8.
