### ISSUE TITLE
Don't restore map when cleaning is not finished

### ISSUE THREAD

**Issue by radokristof** [rand256/valetudo#276]
The new restore map function works great! When the robot returns to the dock, the correct map is loaded.
However if the robot returns to the dock because the battery is low (<20%), the map gets restored here as well, meaning that it won't resume the cleanup.

Would it be possible to add a check to only restore the map if the battery is >20%?

Thanks!

**Comment by rand256** [comment]
Oh, I always forget about that smart-charge mode since I never could discharge the vacuum below 20% during cleaning... I've just made a [test build](https://erinome.net/valetudo-0.9.7-20200804.tar.gz) that should handle that more properly: in theory it should reload a map only when cleaning is complete - regardless of the battery level.

Also this build has a new feature that configured cleaning timers should be tied to the loaded map. Though it's more important for multifloor setups. Anyway, I'd suggest just to re-save your current map so it would add timer settings to a backup so they could be restored later.

**Comment by radokristof** [comment]
Thanks for your quick response!
I will test it soon! My battery is not that great nowadays that's why it usually have to take a quick charge to finish the cleanup. When it was new, the cleaning finished with around 50% battery...

**Comment by radokristof** [comment]
Something is not right with this build for me. After starting a cleanup, it stops cleaning after a few seconds with "Cleanup is finished"

**Comment by rand256** [comment]
That's weird, I can't reproduce it. And AFAIK there were no changes since initial 0.9.7 that could lead to this. Is it saying exactly "cleanup finished", not something about "cleanup stopped"? Valetudo can stop cleaning (using miio command), but it has no way to mark it finished - it's only base firmware that can do it.

I suppose you're running zoned cleaning, is the selected zone far from charging station? Could you try running the cleaning of the room in which the dock is located, would it also be finished immediately in this case?

**Comment by radokristof** [comment]
It seemed a temporary error, everything works correctly. Thanks!

**Comment by radokristof** [comment]
@rand256 This seems to be the case on new builds now again.
It restores the map, so it won't finish the cleaning.
