### ISSUE TITLE
Dock Auto Return when already docked

### ISSUE THREAD

**Issue by hadeshimself** [rand256/valetudo#286]
I just found my robot roaming around in the middle of the night on a mission to find its base because there was a power outage and it went into the idle state. It was already docked, but since the dock was not powered up the robot assumed it was away from it.

Wouldn't it be possible to check the distance from the base before going back to it, assuming the base is saved on the map? Or just save somewhere that it's docked.

Thanks!

**Comment by rand256** [comment]
Strictly speaking, it technically works correctly - on power outage robot leaves its charging state, so it thinks that it has left the dock since it doesn't get charged anymore...

Checking coordinates or writing a variable upon entering or leaving the dock is problematic cause the device is made so it always knows its state but knows nothing about its location - we need to manually fetch, unpack and parse the map for that; similarly we can easily know that device has reached the dock only by the its state being changed to "charging". Still I'll try to see if we can do something about coordinates when processing dock auto-return, but it's not that straightforward unfortunately.

**Comment by hadeshimself** [comment]
I agree. It's a nice feature, but I wouldn't go into much trouble to solve
it.

Only if you assume that once it was charging and no clean/goto/etc action
was taken it is still on its base. If it's idle on the base and the state
goes to 2 (Charger disconnected) maybe don't do anything regarding the auto
dock if the previous state was 8 (Charging)?

Luis

**Comment by barrenechea** [comment]
Mine doesn't move when I unplug the charger from the wall 🤔 (S50 gen2 on the latest firmware)

**Comment by rand256** [comment]
@SebastianBar, if you have auto-return-to-dock enabled in valetudo settings, the device after a specified delay will definitely try to locate the dock if it suddenly gets disconnected. I've already implemented some workaround for this, it will be included into the next release.

**Comment by rand256** [comment]
Should be fixed in 0.9.8.1.
