### ISSUE TITLE
Improve documentation status/question about upstream and supported devices

### ISSUE THREAD

**Issue by hillbicks** [rand256/valetudo#292]
Hey guys,

I just stumbled upon the video to root the S6 and was quite surprised by this since I was under the impression that the only supported devices are the gen1 and S5. Then I realized that valetudo upstream from Hypfer has had a lot of releases since I last looked with support for additional devices. So my questions are: 

1) Is this valetudo release implementing the changes that are made by Hypfer or are these developed completely separately since the fork? 
2) Where can I see the supported devices for this valetudo versions and what is currently supported?

If we clarify these things a bit better, the wiki and README could really benefit from this and I'd be more than happy to help out here. 

Thanks!

**Comment by rand256** [comment]
1. I'm totally not aware of what's going on in origin valetudo version the last months, and RE version won't be implementing their changes in any way.

2. The RE version supports only gen1 and S5, this is clearly written in the beginning of the README. Though I guess it can run well on S6 too, but I don't have the hardware to check. If you could start valetudo daemon on your device and send me some results from http://device_address/api/current_status, I'd be able to say more. In theory it might work on S6 without any changes since S5 firmware versions 2xxx should be quiet similar to S6's ones.

**Comment by hillbicks** [comment]
Thanks for letting me know. I was asking since it is a fork, maybe upstream changes would still make their way into this version. May I ask why their changes won't be implemented though?

And in regards to the robot. I currently own a gen1 and the S55, both running valetudo RE. While looking for a replacement for the gen1 I found it incredibly hard to find a good deal for the S5. Most of the S6 deals are better. I guess I'll have to look at valetudo then and see which devices they support and if one them fit my needs.
