### ISSUE TITLE
Problem with Telegram API and PiHole

### ISSUE THREAD

**Issue by k1ngstire** [rand256/valetudo#297]
Hello there,
today i have set up PiHole, since then my Telegram Connection to the Bot does not work anymore. Everything else works fine.

I think it gets blocked by PiHole but i can not whitelist it because my PiHole runs in a Container which bridges all traffic, so i could only whitelist all the traffic.

So i need another Solution. Is there a way to set the DNS Server of the Bot manually? Like if i would point the DNS of the Bot to 8.8.8.8 or something else public DNS it would not anymore get the DNS Server by my Router and would avoid PiHole.

Thanks in advance.

**Comment by pidator** [comment]
I'm using Pihole too, no problems with the telegram api. So it's probably a problem with your configured blacklists or IMHO If you could only whitelist ALL traffic, there's a much bigger problem in your whole setup, because Pihole is INTEND to block and whitelist specific traffic/dns requests... but this is not part of Valetudo RE or the robot.

You can modify the dns server the robot is using in this file: `/etc/dhcp/dhclient.conf`
You'll have to check the man page of `dhclient.conf` how to ignore the DNS server provided by your DHCP Server and use an specific one.

**Comment by k1ngstire** [comment]
> I'm using Pihole too, no problems with the telegram api. So it's probably a problem with your configured blacklists or IMHO If you could only whitelist ALL traffic, there's a much bigger problem in your whole setup, because Pihole is INTEND to block and whitelist specific traffic/dns requests... but this is not part of Valetudo RE or the robot.
> 
> You can modify the dns server the robot is using in this file: `/etc/dhcp/dhclient.conf`
> You'll have to check the man page of `dhclient.conf` how to ignore the DNS server provided by your DHCP Server and use an specific one.

Okay thank you. I guess you are right. Running PiHole inside Docker inside a LXC might not be the best idea. Atleast i should not using a network bridge and switch over to macvlan so PiHole gets an own IP by my Router and can whitelist/blacklist single devices.

Ill try to change my setup.
