### ISSUE TITLE
[Question] Command on vacuum/MQTT command to load "Stored Map" automatically?

### ISSUE THREAD

**Issue by kalyway101** [rand256/valetudo#305]
I was going through the issues and searching for a way to save previous maps on my Gen1 vacuum. I saw the experimental multi-map buttons under `Settings->Web Interface` and enabled them.

These settings work GREAT for storing and loading a previously saved map to the vacuum!! However, I would like to automatically restore a map just in case the power button (start cleaning button) is pressed. Instead of manually doing this via the Web interface every time.

 Is there a command that I could execute via SSH or MQTT that loads a previously stored map?

Thank you!

**Comment by kalyway101** [comment]
There is an "Auto map restore" function when it returns to the dock, and I can specify what map I would like to use, so if the button is pressed, and it starts a new cleaning, my old one will be restored when it goes back to the dock and zones will still work.

The setting is under Settings->System Settings

**Comment by rand256** [comment]
There's MQTT custom command "load_map" as well as you can call "/api/load_map" via HTTP PUT request.
Unfortunately both require reading [the](https://github.com/rand256/valetudo/blob/testing/lib/MqttClient.js#L590) [code](https://github.com/rand256/valetudo/blob/testing/lib/webserver/WebServer.js) to see parameters, since nobody has written the separate docs yet.

**Comment by kalyway101** [comment]
That is incredibly useful information. I'm surprised no one has documented ALL the commands yet. Thank you!
