### ISSUE TITLE
Clarification : what "last_bin_full" means? I

### ISSUE THREAD

**Issue by jokerigno** [rand256/valetudo#338]
**Describe the bug**

It's not a bug but a clarification. I see that there's a topic called  "last_bin_full"  but I cannot understand what does it means.

I thought that value would change from "0" to "1" when bin becomes full but it isn't so on my S5 rockrobo running v 0.9.9 with fw 2008.
And I'm sure that my bin was full when I removed it (it started to report error 10 like the filter was dirty).

**Expected behavior**

Status changes from "0" to "1" when bin becomes full 

**Vacuum Model:** S5

**Valetudo Version:** 0.9.9

**Comment by pidator** [comment]
Have a look here https://github.com/rand256/valetudo/issues/336#issuecomment-745077620

@rand256 was explaining `last_bin_full` yesterday by hazard ;) so it should be a timestamp if the firmware is trying to send the associated miio information.

*edit:*
`0` is the default value until receiving the information by the firmware.

**Comment by rand256** [comment]
> Status changes from "0" to "1" when bin becomes full

Unfortunately it's not how roborock decided to provide information to us.

The "filter dirty" error means it was detected that there's an issue with the fan engine having difficulties with blowing the air out of the device, which in most cases is related to either bad filter or dustbin become way too full.

The "Bin full" event on the other hand means only that it's too much time has passed since the bin was ~~cleaned~~ removed from device for the last time. So in fact it's quiet useless information. I.e. if you will vacuum for a long time really clean room, it will eventually report "bin full" event although it's empty. This is exactly how it's done in roborock, since it doesn't have any sensors to detect the actual bin fullness.

**Comment by jokerigno** [comment]
Yeah almost useless. I think I will check again for rockbin for a more robust solution. I already tried it but didn't find a way to start it as a service on boot.
