### ISSUE TITLE
After reload a presaved map, all saved time cleaning is deleted

### ISSUE THREAD

**Issue by truresma** [rand256/valetudo#344]
Hello,

when i try to reload a presaved map, all my saved time cleaning is deleted. i´m on v.9.9 with my S50. Is that normal/- is there a workound? 

thanks

**Comment by rand256** [comment]
All zones, goto targets and timers are kinda "tied" to the map, since in most cases when you load i.e. a map for a second floor you don't want to see there zones and timers that were defined on the first floor. So when you create a new zone or a timer, you need to re-save (overwrite) the map not to lose that settings upon reloading it.

If it's not the case, then please check that the map you're loading actually has a configuration file at `/mnt/data/valetudo/maps/<your_map_name>/valetudo.json` which includes your timers and zones, and we'll try to figure out why it's load loading for you.

**Comment by truresma** [comment]
it`s the same map/floor and i saved the map with the saved time cleaning zones.

in the valetudo.json the following is written: 

`{"zones":[],"spots":[],"ztimers":[],"timers":[[true,"Komplettreinigung","0 14 * * 2,4,6","",1,104],[true,"Küchenreinigung","0 14 * * 0,1,3,5","18",2,104]]}`

but when i reload that map, all timers are going.

**Comment by rand256** [comment]
Well, I suppose I've found the cause for this issue. Could you try replacing valetudo binary in your device with [this test build](https://gv.erinome.net/valetudo-test-201223.tar.gz) and try again please?

**Comment by truresma** [comment]
i don't know how to do this ^^ 

i have done a update everytime through the web interface with the normal zip link, and the md5 hash

**Comment by rand256** [comment]
Please see [this wiki article](https://github.com/rand256/valetudo/wiki/Updating-valetudo-binary-on-2008-firmware) then.

**Comment by truresma** [comment]
ok thanks, i have done it and it works now. thanks a lot.

**Comment by truresma** [comment]
Now the power level is not saving.

It is every time at balanced.
