### ISSUE TITLE
Gen1: Map lost after starting cleanup / "Don't know where I am"

### ISSUE THREAD

**Issue by grumbold** [rand256/valetudo#346]
Hi,

I'm using Gen1; Valetudo 0.9.8.1, FW 4018. Initialized a complete cleanup of the apartment to create the map, placed the zones and saved the map. When I chose certain zones and trigger the cleanup of those, the vacuum starts and after a couple of seconds it stops not knowing where it is. The map is gone as soon as the vacuum starts cleaning. 

Reloading the map and starting a cleanup, leads again to a lost map and the vacuum creates a new one. 

Any suggestions on this issue from your side?
Best regards

**Comment by rand256** [comment]
I doubt that valetudo can change anything in this case, it's rather a firmware issue.

Do you reload the map when the device is standing on the dock? Make it leave the dock and try reloading on the floor then. If you reload the map away from the dock, try doing it otherwise. Device can also lose its orientation when it stands close to the walls if it didn't move there by itself.

PS: I don't have gen1, so my guesses could be wrong.

**Comment by grumbold** [comment]
> Do you reload the map when the device is standing on the dock?

I tried both, on the dock and far away, also near walls or in the middle of a room which should be recognized for positioning. 

My S50 is turning around for getting the position, Gen1 is not, I don't know if it should do the same.

The issue happens also for spotcleaning: Starting spotcleaning works, but it starts with a new map after receiving the spot clean order.

**Comment by pidator** [comment]
From my point of view a Gen1 does only recognize its position on the map in relation to the base station. Sure, at the end of a cleaning run it normally takes about 1-2 min while it's rotating until it starts it's way back to the dock. But this is another "rotation" behaviour compared to the (fast) positioning of a Gen2. 

I've never noticed a Gen1 rotating during/while/before a clean run to "get to know" it's position - simply because it officially doesn't have this feature.

My Gen1 was running every RE version till 0.9.9 (also with base firmware 4018) and I haven't had the issues you described. Zone cleaning and spot cleaning works like a charm.  

> When I chose certain zones and trigger the cleanup of those, the vacuum starts and after a couple of seconds it stops not knowing where it is. The map is gone as soon as the vacuum starts cleaning.

This shouldn't happen!
Have you tried changing the dock position? And created a new map with this new dock position? (For testing purposes a "partial" map should be sufficient). If the map still got erased after starting a zoned cleaning, do you have considered doing a factory reset and start again from the scratch?

**Comment by grumbold** [comment]
Thanks for the feedback!!!
>Have you tried changing the dock position? And created a new map with this new dock position? (For testing purposes a "partial" map should be sufficient). If the map still got erased after starting a zoned cleaning, do you have considered doing a factory reset and start again from the scratch?

Yes, i tried it. 
Update: It could be that it happens when using the save and restore map button function (I know this function from Gen2, so I also tried the same on Gen1). After saving and restoring the map, the map will be erased and zone cleanup is not working.
So I let the Gen1 create a new map for a small room, (I didnt use the save & restore feature) created zones and it worked. It is drinving back to the station and remebers the map. I'll test more.

Does anyone know if the save & restore feature cannot be used on Gen1?

**Comment by pidator** [comment]
> Does anyone know if the save & restore feature cannot be used on Gen1?

I was using the save and restore feature the whole time with my Gen1! I even let it auto restore the saved map when returned to the dock every time. The map got never deleted when starting a new zoned cleaning after restoring the map.

**Comment by flyize** [comment]
> > Does anyone know if the save & restore feature cannot be used on Gen1?
> 
> I was using the save and restore feature the whole time with my Gen1! I even let it auto restore the saved map when returned to the dock every time. The map got never deleted when starting a new zoned cleaning after restoring the map.

I would like to test this. How do I get a Gen1 to save and restore maps?

edit: I was able to find this. Thanks for making me look!
