### ISSUE TITLE
Error 1

### ISSUE THREAD

**Issue by uPagge** [rand256/valetudo#354]
Hello

A week after the update to 0.10.0, I decided to start the vacuum cleaner. I saw that it was no longer available via IP, I decided to launch it by clicking the button, to which I received an answer: error 1. At the same time, the lidar stopped rotating, could it be somehow connected with the update or a problem in the hardware?

**Comment by pidator** [comment]
Error 1 indicates a hardware failure of the lidar unit (here: stopped rotating) and isn't related with Valetudo since it is sent by base firmware and only displayed in Valetudo. Try to search google, there are several possibilities to get the lidar working again, the worst case will be to replace the lidar unit.

**Comment by uPagge** [comment]
I checked the motor that drives the lidar by connecting external power, it works.

But when it is inserted into the vacuum cleaner, it does not rotate even if the belt is removed from it.

I also do not understand why the control interface stopped opening

**Comment by uPagge** [comment]
I described my problem and what I did in more detail, perhaps this will help to understand.

https://blog.upagge.ru/en/posts/guide/smart_home/roborock_error_one/

**Comment by uPagge** [comment]
Oh my god, the owner of the original repository just banned me with my problem, great

@rand256 It definitely can't be related to the firmware?

**Comment by rand256** [comment]
These error codes are generated by the firmware and valetudo just relays them to you as is. The error 1 should be hardware-related I guess, though if you have a plenty of time you may try flashing a different base firmware just to be sure.

**Comment by uPagge** [comment]
@rand256 I'm just embarrassed that the valetudo interface stopped opening. Do you know if this is a normal situation with such errors?

**Comment by rand256** [comment]
I've never had such errors so I don't know, though to me it shouldn't do that.

Does the device is on your wifi network at all? Is a wifi led on the device glowing solid or blinking? Could you connect to the device via ssh? If not, it may somehow decided to factory reset itself so there's just no valetudo on the device anymore.

**Comment by uPagge** [comment]
This is the problem that the device does not connect to my router and the wifi light is off.

**Comment by uPagge** [comment]
@rand256 Is there a way to somehow restart valetudo or reset wifi?

Voice packs remained custom, so the firmware may not have been reset

**Comment by rand256** [comment]
When light is off means the device has wifi disconnected. So you actually can't say that valetudo interface stopped opening since you simply can't connect to the device - maybe valetudo is still there but unreachable.

Though anyway do a wifi reset (see user manual, there's a wifi reset button somewhere depending on the device model), wait until the led starts blinking and search for a new wifi access point started by the device. Connect to it and try opening http://192.168.8.1 (or check the IP you got from the AP and try opening the site on a gateway's IP received (i.e. http://x.x.x.1)). If you'll get into valetudo web interface, just go to the settings and enter the new wifi parameters to re-connect the device to your network. If you'll see timeout connecting, then most likely valetudo is gone and you will need to reflash it again from scratch.

Also you can try opening ssh when connected to the device in AP mode to see what's going on inside if you have some experience in linux.

**Comment by uPagge** [comment]
I tried to reset the wifi but it would not reset. In any case, I found how to reset it to the factory settings, I will write what happens as a result

Thank you very much for your participation

**Comment by uPagge** [comment]
Apparently the problem is partially related to the firmware.

First, wifi stopped working and reset. Secondly, after resetting to the factory firmware, the motor began to spin the lidar, but not fast enough

Then I had a second question, if the lidar is standing or not spinning fast enough, will the laser shine? I do not shine

**Comment by rand256** [comment]
> will the laser shine? I do not shine

What exactly do you mean? Why do you shine as a laser? При чем тут вообще сияние лазера? )) AFAIK the lidar must rotate at the correct pace only for the software to build a map on the captured data. If the engine can't operate as it should, you won't be able to get a proper map anyway. Though in my opinion this should never lead to system failures and/or wifi breakage, but with these Chinese devices you really never know what their manufacturers mentioned in the first place. Аlso I'd never try to look on at the laser cause of safety considerations.

**Comment by uPagge** [comment]
I somehow accidentally noticed during the cleaning process how the laser shines in a normal situation. That is, if you lower your gaze to the level of the lidar, then the laser beam will be visible when it enters the eye, like the light from a conventional laser pointer.

Actually, it seems to me that now the motor does not spin the lidar enough and therefore it does not even start to shine with a laser. I understand that if the speed is not enough, then even the luminous lidar will build the wrong map. But at this moment I am just worried about the general performance of the lidar, maybe it was dead.

In general, my next goal is to change the motor, since a friend from my city has a suitable one, so I will soon continue my observations

**Comment by uPagge** [comment]
The problem still turned out to be in the motor. Replaced with a new one.
