### ISSUE TITLE
Webserver noch working after update to 0.10.3

### ISSUE THREAD

**Issue by MHS-NETwork** [rand256/valetudo#374]
The webserver is not working after the last update via webinterface

**How to Reproduce**
The device reacts on ping. Nothing else changed. Cockies/ cache cleared. Multiple devices tried. SSH access is possible. Last firmware is installed (2034). Website responds "ERR_CONNECTION_REFUSED" on the IP address. Device was restarted multiple times. 

**Expected behavior**
An functional webinterface

**Vacuum Model:** S55

**Valetudo Version:** last (0.10.3)

**User-Agent** Win10, Chrome and Android 10, Chrome

**Additional context**
If there is any solution to start the webserver via SSH manually or retry the update, pls tell me.

**Comment by pidator** [comment]
Is Valetudo running? You can start/stop it manually with
`/etc/init/S11valetudo start` or `/etc/init/S11valetudo stop`

**Comment by MHS-NETwork** [comment]
Thank you for the fast response. The file is missing.  

> root@rockrobo:# /etc/init/S11valetudo start
> -bash: /etc/init/S11valetudo: No such file or directory
> root@rockrobo:# cd /etc/init/
> RRENV             S02network        S04wdgenv         S10rc_local       logrotate.conf    snmpd.conf
> S00mounted-dev    S03kmod           S05crond          S12soundserver    mountall.conf     wifi.bak
> S01logging        S03mountall       S06adbd           adbd.conf         rcS
> S02hostname       S04bootring       S09snmpd          bootring.conf     rrwatchdoge.conf
> root@rockrobo:~# cd /etc/init/

**Comment by pidator** [comment]
What firmwarefile do you have installed? You could also check if the valetudo binary is placed in `/usr/local/bin/`. If not, you've probably installed a firmware without preinstalled valetudo.

**Comment by MHS-NETwork** [comment]
on the ssh-Loggon screen it's 2034 printed ( FIRMWARE........: 3.5.8_002034; BUILD NUMBER....: 2020112701REL), but the folder you sent is nearly empty. Only these three files are in:
> phrases.sh       rrlogclean.sh    sound_server.pl

**Comment by pidator** [comment]
yes, so you've probably flashed your vacuum with just a rooted firmware without valetudo. 
that's why I'm asking which _specific_ firmwarefile do you flashed!? Do you used a prebuild image or built the firmware by yourself?
 
So I would recommend following the [installation instructions](https://github.com/rand256/valetudo/wiki/Installing-valetudo-binary-on-2008-firmware) for a new clean installation.

You're issue is not valetudo related, simply because valetudo isn't installed on your robot :)

**Comment by MHS-NETwork** [comment]
Sorry you're right. I forgot to send you the link. https://github.com/rand256/valetudo/releases/download/0.10.3/vacuum_2034_valetudo_re_0_10_3.pkg

**Comment by pidator** [comment]
> https://github.com/rand256/valetudo/releases/download/0.10.3/vacuum_2034_valetudo_re_0_10_3.pkg

I've just verified this file: This image definitely contains the valetudo installation!
The content of the folder `/usr/local/bin` is
```
bbfs
rrlogclean.sh
valetudo
valetudo-daemon.sh
```

but following your answer here
> but the folder you sent is nearly empty. Only these three files are in:
> 
> > phrases.sh       rrlogclean.sh    sound_server.pl

I conclude you did not flash the named file - more an other image file, because `phrases.sh` and `sound_server.pl` are additional addons that e.g. can be added by the [zvldz-imagebuilder](https://github.com/zvldz/vacuum/) (see [this code example](https://github.com/zvldz/vacuum/blob/5a091ad36458212a749ab371449fcc27c07b2424/custom-script/custom_random_phrases.sh#L54) for reference).

You will have to flash the prebuild image again (or try to install valetudo manually). Depending on your linux skills it will probably be easier to simply flash the correct image again.

**Comment by MHS-NETwork** [comment]
Thanks for you're help. I flashed the named (correct) file via WebUI. What you see is a language pack what I have installed on the 0.9.9 version. So everything is stock, excepting the language pack. I think we will not find the reason why the upgrade failed. 

The solution was to flash the image with XVacuum again. I manually ensured the token I got via SSH, so I can keep my settings and now everything is working well.
