### ISSUE TITLE
Only lower letters in status on map view.

### ISSUE THREAD

**Issue by MadJoker0815** [rand256/valetudo#40]
When switching to german language, the status only displays lower letters. Like on "Rückkehr zur Basis" it actually displays "rückkehr zur basis".

In the language file it is written with capital letters. Also the status is correct on the main page.

Tested on Gen1 with Valetudo RE7.1
Just switch to german language and then to the map. In the status box the status itself is displayed in lower case letters. The word "Status" and "Akkustand" are correct.

**Comment by rand256** [comment]
This is intended. It changes letters to lowercase by [this instruction](https://github.com/rand256/valetudo/blob/testing/client/locales/en.json#L91) because in some languages it is customary not to use uppercase after the colon.
To stop it from doing so it is required to remove `, lowercase` part from that line.
