### ISSUE TITLE
[mqtt] feature request: expand play_sound capabilities

### ISSUE THREAD

**Issue by Setsua** [rand256/valetudo#402]
I played  around with the play_sound feature which is great to play a file on certain actions. But I really want to use my vacuum as an internet radio. Is it possible to implement m3u playback capabilities? Ideally I would like to predefine m3u radio stations in HomeAssistant and let my vacuum play whatever I have choosen. I also noticed play_sound ignores the volume setttings and plays them at full volume. Additionally I noticed play_sound is blocking the sound device so if I start my vacuum while a sound file is being played I get no voice response.

**Comment by pidator** [comment]
Since you labeled your "issue" as a "feature request" by yourself, I would recommend using the [ideas section](https://github.com/rand256/valetudo/discussions/categories/ideas) of the discussion section to post your idea.

> I also noticed play_sound ignores the volume setttings and plays them at full volume. 

Have you read the [wiki article](https://github.com/rand256/valetudo/wiki/MQTT-API#topic-valetudorockrobocustom_command)  about the mqtt commands? You can change the volume with the additional parameter `volume`.

> But I really want to use my vacuum as an internet radio. Is it possible to implement m3u playback capabilities? Ideally I would like to predefine m3u radio stations in HomeAssistant and let my vacuum play whatever I have choosen. 

This sounds more like a firmware modification than a Valetudo option. Have you tried building the firmware by yourself with [custom sound server](https://github.com/zvldz/vacuum/blob/master/custom-script/custom_sound_server.sh) installed? Perhaps this can be also used to play m3u files, idk...

Edit:
> Additionally I noticed play_sound is blocking the sound device so if I start my vacuum while a sound file is being played I get no voice response.

I've never used it, but I think without SoX being installed as a separate player there's only sound **or** voice with the default player possible, not both together. While playing the music instead with SoX, the voice could still be possible.

**Comment by Setsua** [comment]
> Since you labeled your "issue" as a "feature request" by yourself, I would recommend using the ideas section of the discussion section to post your idea.

And I googled before how to post feature requests and the answer was "there is no feature request functionality since pull request is only for constributors. Write an issue and tag it as feature request." *facepalm*

>  Have you read the wiki article about the mqtt commands? You can change the volume with the additional parameter volume.

Also google for valetudo mqtt commands but came up only with parted information. It was right here. Omg

> I've never used it, but I think without SoX being installed as a separate player there's only sound or voice with the default player possible, not both together. While playing the music instead with SoX, the voice could still be possible.

Unfortunately not. "snd_pcm_open error: Device or resource busy"
