### ISSUE TITLE
Feature request: WiFi signal level on map

### ISSUE THREAD

**Issue by hawkeye223** [rand256/valetudo#44]
Is it possible to display the measurements of the level of the wifi signal on the map? In order for the robot to draw a coverage map, he wrote a color line where he drove a legend with the appropriate level, for example, red - the signal is less than 80, green - 50, etc.
Just for fun)

**Comment by rand256** [comment]
While it might be cool, it's not that useful after all (wifi receiver is of a poor quality on these devices anyway and its driver software probably too - just to see the amount of warnings in dmesg), and also it is not clear on how actually code that.

The path is written not by valetudo but native vacuum's software to the separate place and then automatically packed with the binary map. We have recently moved map parsing from the vacuum to client devices since unpack->parse->pack sequence on the vacuum is bit difficult task for its CPU. Also, the path is stored only as a set of points without any time marks when those points were taken, so there's almost no simple way to correlate it with signal strength data possibly collected by the vacuum.

**Comment by TheMicroDevil** [comment]
Hm, just for fun.... we do not need any timestamps...if you forget the lines

- We check xPos/yPos every 5 seconds, as it was possible early days with "/api/remote/map"
- And we check current wifi strength too
- We now have coordinates and strength

Now the magic has to happen and i am no mage
- The client does the job, not the robot
- Every 5 second we push the current data string to clients e.g. {"x":300,"y":500,"w":"80%"}
- On client we add an additional overlay over the map
- On every recorded or received coordinate we will draw a bunch of pixels, maybe a circle, somewhat transparent or blur it
- The color will base on signal strength 

voilà - real time wifi strength map thingy
