### ISSUE TITLE
Feature possible?: Wifi Roaming

### ISSUE THREAD

**Issue by LichtiMC** [rand256/valetudo#453]
I wonder if it's technically possible to implement some sort of "manual wifi-roaming".
For example, if the signal strength goes down below a specific value, a reconnect is being issued by valetudo.

I have 2 Accesspoints at home and unfortunately the signal gets lost if the vacuum robot drives away too far from AP1, even though it would have full strength wifi signal from AP2. (Of course SSID and keyphrase are the same on both APs)

**Comment by pidator** [comment]
iirc the wifi configuration of the base linux firmware of the robot (which is responsible for the wifi connection - not the valetudo gui) does not contain the roaming functionality like you're used to have on other devices like laptops or smartphones. The robot connects to one `BSSID` (exactly one AP) and keeps the connection as long as this `BSSID` is within reach. That's why the wifi roaming in spite of a second AP with the same `SSID` is not working. I might be wrong, but that's how I remember the situation.
