### ISSUE TITLE
[Request] DND Times

### ISSUE THREAD

**Issue by Madaraxa** [rand256/valetudo#470]
**Feature to add DND Times when the robot wont 'speak' **

**How to Reproduce**

This night (First night after flashing valetudo re) my roborock s50 played a melody and said something like 'Update complete' at 3:11 AM. The robot is parked beside my bed so it was kinda disturbing. 
I got a DND inside the timers section (by default) and this one didnt avoid the voice output. 

**Expected behavior**

Add DND Times where there is no Sound output (maybe combined with disabling the led?) 

Thanks in advance

**Comment by pidator** [comment]
this sounds more like an factory reset of the robot after the daily reboot (that usually happen around 3 am in europe time zone) than an "update" sound? Dou you checked the robot the next day? Do you had to reflash again?

The actual function of the DND timer provided by the roborock firmware is to stop the robot resuming a clean run if it had to drive back to the dock to recharge because of low battery. There's no dedicated suppression of the sounds!

**Comment by Madaraxa** [comment]
Hi.
I have still valetudo on the robot. No need to reflash. And this night He didnt make any sounds.
So it isnt disturbing any more.
I'm not completely sure what words he said.
First there was a melody I havent heard pre-valetudo and then it might habe been something other than 'Update complete', but I'm sure of the Word 'Update', as I thought to myself how unlucky I was that I got an Auto Update the night after flashing :)

**Comment by rand256** [comment]
What you are describing is likely due to bugs in underlying manufacturer's firmware, it can't be fixed in third party tools like valetudo.

I guess even if the sound volume was reduced to zero, the "Update complete" message will still be played cause it it like "service notification" scheduled to be run after the first reboot after firmware (re)installation. In your case by some reason it didn't happen at the right time, so you've got it after the next reboot - which is, unfortunately, what the device does every night.

**Comment by Madaraxa** [comment]
Oh ok.
This would make sense as I didnt reboot the robot after flashing manually.
And if you cant 'DND' Service notifications my Request can be closed. Normal notifications shouldnt be an issue as the robot wont be controlled by someone as soon as we are sleeping :)

**Comment by rand256** [comment]
The thing is it should have itself reboot _and_ played the scheduled notification immediately - and generally you never need to reboot it manually.
But it looks like something glitched this time.

Maybe manually turning off and on again after changing a firmware isn't a bad idea to prevent cases like this one though...

**Comment by Madaraxa** [comment]
Yeah. In the manual of the 'normal' valetudo is a last step to reboot the robot.
As it was missing in valetudo re I didnt reboot after flashing :)
