### ISSUE TITLE
Roborock starts cleaning after saving MQTT settings

### ISSUE THREAD

**Issue by Babelbernd** [rand256/valetudo#519]
Hello everyone. 

I flashed the newest Version of this Firmware to my Roborock S50 and made the MQTT Setup. Everything works fine except my Roborock starts cleaning after saving any MQTT settings. But the even worse Thing is, my roborock also starts cleaning everyday at 3:31 in the morning. When i deactivate MQTT everything works fine. Can anyone reproduce this issue?

**Comment by Babelbernd** [comment]
I Just found out that both of my Roborocks repeat the last MQTT i published everyday at 3:31 in morning. For example when i send the 'find my robot' command sometime in the afternoon, it does it again everyday at 3:31am 🤷

**Comment by pidator** [comment]
I'm not quite sure but iirc this has something to do with your broker settings and the fact, that the robot will automatically reboot at this time. I can't remember exactly but it was a setting about resending a message or redo an action after a devices connects again to the broker.

**Comment by pidator** [comment]
Check [this issue](https://github.com/rand256/valetudo/issues/448)

**Comment by sca075** [comment]
@Babelbernd as @pidator advised, it looks that the robot at 3:31am is disconnecting and then re-connecting to the network. I'm writing this because I do have with my provider the same issue, I mean at 3am around the router get a new IP and disconnect and re-connect all devices in the network. I would therefore advise to check if the router is disconnecting the robot at that time... (it can be a simple network issue).

**Comment by pidator** [comment]
There is a daily reboot script in the robots firmware that run between 3 and 4 am! It will definitely disconnect from the network every night ;)

**Comment by Babelbernd** [comment]
That restart is exactly my Problem. I did not delete the MQTT Message after sending. Thats why my roborock executed the Last command again. Thanks for your Help 👍
