### ISSUE TITLE
Feature request: MqttClient.CUSTOM_COMMANDS.PLAY_SOUND

### ISSUE THREAD

**Issue by webcharlyx** [rand256/valetudo#56]
would be really great to directly .aplay a local file on MQTT trigger (e.g. [node-aplay](https://www.npmjs.com/package/node-aplay)?)

**Comment by Stefan300381** [comment]
I second this request as I load map via mqtt and never know if the command was received successfully. Im on latest gen 2 fw and version

**Comment by rand256** [comment]
> I load map via mqtt and never know if the command was received successfully

Wouldn't it be better to create a new topic where the results of processing received commands will be published then? Or this won't be convenient to use? I'm asking since I personally am not using mqtt so I don't know which are the possibilities of home automation apps.

**Comment by Stefan300381** [comment]
indeed, but I haven't seen (maybe I'm blind ;-) ) any topic that shows which map is loaded.

EDIT: oh wait, you mean you could implement this? yes, this would be the better solution for my specific use case. not sure why webcharlyx requires the sound functionality

**Comment by rand256** [comment]
So I've added both mentioned suggestions: "play_sound" custom command and a kind of logging to "command_status" topic.

The new custom command has the following payload:
```
{
   "command": "play_sound",
   "file": "/opt/rockrobo/resources/sounds/power_on.wav"
}
```
The file should be in wav format, it is played via `uart_test` tool (so it is already available on the device, though nobody can guarantee that it will be present in future firmware versions).

And the "command_status" topic has the following data:
```
{
   command: <corresponding command name the report is about>,
   message: <null if error occurred or optional text if command succeeded>,
   error: <null if command succeeded or error description if command failed>,
   updated: <current unixtime in ms>
}
```

I've uploaded a [test build](https://erinome.net/valetudo-0.9.5-20200618.tar.gz) with these changes so it's possible to check whether it works correctly in different circumstances and if something should be changed before this goes into the release.

**Comment by Stefan300381** [comment]
thanks for your invest, just tested the release. 

unfortunately it doesn't really help me. Here is what I'm looking for:

Current situation with test build:
* REQUEST
`{\"command\": \"load_map\",\"name\": \"1stFloor\"}`
* RESPONSE
`{"command":"load_map","message":"ok","error":null,"updated":1593004021163}`

Desired situation:
* REQUEST
`{\"command\": \"load_map\",\"name\": \"1stFloor\"}`
* RESPONSE
{
  "configuration": {
    **"map": "\"1stFloor\"",**
    "speed": "\"normal\""
    etc.
  }
}

**Comment by rand256** [comment]
Why would you need to know which map was loaded? If the error is null and message is like 'ok', then the current map is exactly that you've requested in load_map's name argument.

Actually, valetudo itself doesn't know what is the current map: when you ask it to restore the map it just takes a saved map and copies it over the current one. What would happen with the current map next valetudo has no idea of. For example, device's firmware may reset it at some point (i.e. if you bring the device to unknown place), and all the third party applications including valetudo will never know about it. Because of that I'm not sure that making valetudo keep in memory which was the last loaded map name could be ever useful.

**Comment by Stefan300381** [comment]
Get your point, but still want to answer your question "Why would you need to know which map was loaded?"

My use case is that I'm using a home automation system, openHAB. Here I remote control valetudo via MQTT.
When I'd like to clean the first floor I send the command to load the right map. ONCE I know this was successful, I send the command to do a room cleaning (selected rooms).

I think I can still work around the current implementation from the test release. maybe like this:
- openHAB monitors the mqtt response, e.g. permanently stores the value inside a variable and updates it whenever valetudo pushes a new mqtt message
- if I send the load map command I have to note the current timestamp using internal openhab methods
- when I receive the load_map response message I compare my sent timestamp with valetudo response timestamp. 
- this way I make sure that the response I received is newer than the command I sent. otherwise my response variable might contain an old response to an old command.

just thought about a different approach. in sense of transparency I share it here:
- once I send the load map command I use a boolean variable that tells me I'm currently waiting for a response
- as soon as the mqtt response variable has been updated, I check if bool = true and set it to false. then I issue the clean room command.

**Comment by rand256** [comment]
I thought the combination of "command" + "updated" fields should be enough to exactly distinguish responses to one command from another granted the home automation system used can remember the received time mark and use it for comparison later. I suppose this is the universal and most lightweight way since it'll work for any command likewise and doesn't require producing specific output for each command.

**Comment by Stefan300381** [comment]
all good. works like a charm! thanks a lot. I created a video (unfortunately in German). 
First I select the map, then it waits until it got the mqtt response and lets me choose which rooms to clean. then I issue the clean command. What you see is usually used via a tablet attached to a wall.

https://youtu.be/zKcTEi_5ZHY

**Comment by Dodoooh** [comment]
how can I run the play sound command? 
unfortunately, it doesn't work that way: 
`{"command":"play_sound","file": "/opt/rockrobo/resources/sounds/power_on.wav"}`


it doesn't work that way either: 
```
{
   "command": "play_sound",
   "file": "/opt/rockrobo/resources/sounds/power_on.wav"
}
```

but commands like "locate" or similar I can send

**Comment by rand256** [comment]
@Dodoooh, in general - check `/var/log/upstart/valetudo.log` file or `../command_status` MQTT topic for errors.

> but commands like "locate" or similar I can send

"locate" should be sent to `../command` topic while "play_sound" - to `../custom_command`. Though the format is different anyway.

**Comment by Dodoooh** [comment]
i didn't know that! so it works of course thanks a lot and also great work :)
