### ISSUE TITLE
Firmware 1910 safe for Gen2? 

### ISSUE THREAD

**Issue by MaluNoPeleke** [rand256/valetudo#59]
The original Valetudo page warns about installing firmware 1910 for Gen2 but on the firmware page there is a version including Valetudo RE: https://vacuumz.info/download/gen2/vacuum_valetudo_re_1910.pkg
Is it safe to use? 
I just discovered the whole Valetudo thing today.

**Comment by rand256** [comment]
The whole issue with 1910 version and above is that in stock images you'll lose the ability to flash anything else on top of that versions unless you do a factory reset. However in current Valetudo RE there's a workaround to initiate flashing newer versions even in that case (done via web interface and not 3rd party apps). Though it's not thoroughly tested.

As far as I understand, valetudo images on vacuumz.info are not "stock" and probably have another workaround for this issue - embedded miio client downgraded to pre-1910 version that is.

Rather than that there's no issues with 1910. Stock image of 2008 however also has ssh port heavily blocked in addition to be unable to be flashed.
