### ISSUE TITLE
Firmware-Update: What's the "send request" button about?

### ISSUE THREAD

**Issue by pidator** [rand256/valetudo#78]
In the setting of Valetudo RE there's an additional line "Firmware update:" in the section "Info".
There's just a link described with [send request]. What is this Link about? Will it download/install a newer (official) Mi firmware? Is it save to push the button and not to lose Valetudo?

Thanks for explaining.

**Screenshots**
![firmwareupdate](https://user-images.githubusercontent.com/59822549/72378932-a9724a00-3712-11ea-91be-feb47c9263bb.jpg)

**Vacuum Model:** Gen1
**Valetudo Version:** 0.8.1

**Comment by rand256** [comment]
It makes the device update firmware from user-specified URL. With 0.8.2 it works even with 2008 firmware (at least with miio downgraded to 3.3.9 in vacuumz.info images, 3.5.7 not tested yet).

**Comment by pidator** [comment]
I do understand, thanks. Havn't clicked on request yet without any instruction ;-)

**Comment by alexschomb** [comment]
Just to get it right: We need to input the URL of the pkg file from the releases and the URL of the md5 file from the releases? Because if I just input the MD5 hash instead of the MD5 file URL it won't be accepted - although the description states otherwise.

**Comment by rand256** [comment]
It requires to input just md5 hash, but this works only in 0.8.2+.

**Comment by Malakai-DB** [comment]
@rand256 
Sorry to post a comment on a closed topic, but I have a couple of questions regarding firmware update from the "send request" button and thought it would be better to write them here than open a new issue.

I have a Xiaomi Roborock S50 v2 that I flashed a while ago.
It has the firmware version 3.3.9_001518 and Valetudo RE version 0.9.3
I would like to update the firmware with the "send request" button to the latest release (vacuum_2020_valetudo_re_0_9_6.pkg).

1) Is it safe to do it this way (going from 1518 to 2020)? No side effects (bricking)?
2) Would I have to reconfigure everything on the vacuum? WiFi connection, timers, ssh, etc? Or will it be able to save these configurations and import them after the firmware upgrade?

I am asking because I don’t want to brick my vacuum (I am not sure I would be able to unbrick it) and it became necessary in the house (my wife would kill me if it would not work anymore, even for a couple of days).

Thanks

**Comment by rand256** [comment]
You can _always_ reset the device to factory settings if anything goes wrong, so it's almost unbreakable.

> Is it safe to do it this way (going from 1518 to 2020)?

I don't know if anyone did that in these exact versions: I've upgraded firmware multiple times though in smaller steps. But I suppose everything should go fine.

> Would I have to reconfigure everything on the vacuum? WiFi connection, timers, ssh, etc? Or will it be able to save these configurations and import them after the firmware upgrade?

In normal case, no settings would be lost. But I'd save at least the map (in valetudo) and copy /mnt/data/valetudo directory from the device to the PC/smartphone just in case.
