### ISSUE TITLE
Changing Zones Order may not function as intended

### ISSUE THREAD

**Issue by nicedevil007** [rand256/valetudo#8]
Hi rand256,

today I started a greater cleaning of 5 zones.
You give us the choice to rearrange the order of how the zones should be cleaned up.

Maybe there is a little bug with 2 zones that overlap each other? My robot did the 2nd zone first.

![image](https://user-images.githubusercontent.com/17103076/61182138-8cf43880-a62f-11e9-9265-3deebd0d0d12.png)

**Comment by rand256** [comment]
Valetudo can't influence on exactly what and how the vacuum's firmware does. Cleaning order usually directly depends on the order in which zone coordinates were passed to the firmware. Maybe there are some exclusions from this rule. Nevertheless it can't be changed from the Valetudo's side.

**Comment by nicedevil007** [comment]
Ok thx, just clearing this up :)

**Comment by rand256** [comment]
I've just seen this issue myself, and the zones were not even overlapping.

I assume this is a bug in roborock firmware. Looks like it happens when the device leaves the dock and starts rotating to detect its own position. Sometimes it may have some issues with it (which looks like the vacuum just stands still for some dozens of seconds), and after that it may start cleaning but in shuffled order.

I can only suggest to complain about this to roborock support hoping they could make firmware devs to fix this.
